/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qARqpE4p5tZmJuNxFbTaPz
// Component: Ok7oDnvmXicS

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicItemStaffs2.module.css"; // plasmic-import: Ok7oDnvmXicS/css

import Icon20Icon from "./icons/PlasmicIcon__Icon20"; // plasmic-import: Sy9FntGzJUck/icon

createPlasmicElementProxy;

export type PlasmicItemStaffs2__VariantMembers = {
  booking: "booking";
  home: "home";
  status: "offersReceived";
};
export type PlasmicItemStaffs2__VariantsArgs = {
  booking?: SingleBooleanChoiceArg<"booking">;
  home?: SingleBooleanChoiceArg<"home">;
  status?: SingleChoiceArg<"offersReceived">;
};
type VariantPropType = keyof PlasmicItemStaffs2__VariantsArgs;
export const PlasmicItemStaffs2__VariantProps = new Array<VariantPropType>(
  "booking",
  "home",
  "status"
);

export type PlasmicItemStaffs2__ArgsType = {
  item?: any;
  onClick?: (event: any) => void;
  goToCenter?: (event: any) => void;
  goToDetails?: (event: any) => void;
  offer?: any;
  loading?: boolean;
  onLoadingChange?: (val: string) => void;
};
type ArgPropType = keyof PlasmicItemStaffs2__ArgsType;
export const PlasmicItemStaffs2__ArgProps = new Array<ArgPropType>(
  "item",
  "onClick",
  "goToCenter",
  "goToDetails",
  "offer",
  "loading",
  "onLoadingChange"
);

export type PlasmicItemStaffs2__OverridesType = {
  root?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  svg?: Flex__<"svg">;
};

export interface DefaultItemStaffs2Props {
  item?: any;
  onClick?: (event: any) => void;
  goToCenter?: (event: any) => void;
  goToDetails?: (event: any) => void;
  offer?: any;
  loading?: boolean;
  onLoadingChange?: (val: string) => void;
  booking?: SingleBooleanChoiceArg<"booking">;
  home?: SingleBooleanChoiceArg<"home">;
  status?: SingleChoiceArg<"offersReceived">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicItemStaffs2__RenderFunc(props: {
  variants: PlasmicItemStaffs2__VariantsArgs;
  args: PlasmicItemStaffs2__ArgsType;
  overrides: PlasmicItemStaffs2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "booking",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.booking
      },
      {
        path: "home",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.home
      },
      {
        path: "status",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.status
      },
      {
        path: "loading",
        type: "writable",
        variableType: "boolean",

        valueProp: "loading",
        onChangeProp: "onLoadingChange"
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_qARqpE4p5tZmJuNxFbTaPz",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootbooking]: hasVariant($state, "booking", "booking"),
          [sty.roothome]: hasVariant($state, "home", "home"),
          [sty.rootstatus_offersReceived]: hasVariant(
            $state,
            "status",
            "offersReceived"
          )
        }
      )}
      onClick={args.onClick}
    >
      <div
        className={classNames("all", sty.freeBox__kSAb)}
        onClick={async event => {
          const $steps = {};

          $steps["runGoToCenter"] = true
            ? (() => {
                const actionArgs = { eventRef: $props["goToCenter"] };
                return (({ eventRef, args }) => {
                  return eventRef?.(...(args ?? []));
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["runGoToCenter"] != null &&
            typeof $steps["runGoToCenter"] === "object" &&
            typeof $steps["runGoToCenter"].then === "function"
          ) {
            $steps["runGoToCenter"] = await $steps["runGoToCenter"];
          }
        }}
      >
        <div className={classNames("all", sty.freeBox___8W66F)}>
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img, {
              [sty.imghome]: hasVariant($state, "home", "home")
            })}
            displayHeight={"100%"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"100%"}
            height={"100%"}
            loading={"lazy"}
            src={
              hasVariant($state, "home", "home")
                ? (() => {
                    try {
                      return (
                        $props.item.main_image ||
                        "https://teh-3.s3.poshtiban.com/lioms3/2026-07/panel/sayban/2026-07-06-0e84ddab-4905-4287-bb45-0050910d90af.png"
                      );
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return {
                          src: "/plasmic/sayban/images/image6.png",
                          fullWidth: 224,
                          fullHeight: 224,
                          aspectRatio: undefined
                        };
                      }
                      throw e;
                    }
                  })()
                : (() => {
                    try {
                      return $props.item.avatar;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return {
                          src: "/plasmic/sayban/images/_3380864Svg.svg",
                          fullWidth: 750,
                          fullHeight: 500,
                          aspectRatio: 1.5
                        };
                      }
                      throw e;
                    }
                  })()
            }
            width={"100%"}
          />
        </div>
        <div
          className={classNames("all", sty.freeBox__jPmwO, {
            [sty.freeBoxhome__jPmwOvEsIk]: hasVariant($state, "home", "home")
          })}
        >
          <div
            className={classNames("all", sty.freeBox__awJcc, {
              [sty.freeBoxhome__awJccVEsIk]: hasVariant($state, "home", "home")
            })}
          >
            <div className={classNames("all", sty.freeBox__toSzM)}>
              <div className={classNames("all", sty.freeBox__m4Hui)}>
                <div
                  className={classNames("all", sty.freeBox__nTxl3, {
                    [sty.freeBoxbooking__nTxl3QdUax]: hasVariant(
                      $state,
                      "booking",
                      "booking"
                    )
                  })}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__ldZxJ)}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $props.item.rating;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "4.5";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__xXfpk)}
                >
                  {"\u062e\u062f\u0645\u0627\u062a \u0645\u0648\u0641\u0642"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__mdZKp)}>
                <div
                  className={classNames("all", sty.freeBox__m9MLz, {
                    [sty.freeBoxbooking__m9MLzqdUax]: hasVariant(
                      $state,
                      "booking",
                      "booking"
                    )
                  })}
                >
                  <Icon20Icon
                    data-plasmic-name={"svg"}
                    data-plasmic-override={overrides.svg}
                    className={classNames("all", sty.svg)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      "all",
                      "__wab_text",
                      sty.text___51NZr
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $props.item.rating;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "4.5";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__nIrqE)}
                >
                  {"\u0627\u0632 6186 \u0627\u0645\u062a\u06cc\u0627\u0632"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__b5MwM)}>
                <div
                  className={classNames("all", sty.freeBox__ly94B, {
                    [sty.freeBoxbooking__ly94BqdUax]: hasVariant(
                      $state,
                      "booking",
                      "booking"
                    )
                  })}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__uwJg)}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return `${$props.item.experience_years} سال`;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "4.5";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__rrwPv)}
                >
                  {"\u0633\u0627\u0628\u0642\u0647 \u06a9\u0627\u0631\u06cc"}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        className={classNames("all", sty.freeBox___4FoUk, {
          [sty.freeBoxhome___4FoUkvEsIk]: hasVariant($state, "home", "home")
        })}
      >
        <div
          className={classNames("all", "__wab_text", sty.text__ft7K9, {
            [sty.texthome__ft7K9VEsIk]: hasVariant($state, "home", "home")
          })}
        >
          {hasVariant($state, "home", "home") ? (
            <React.Fragment>
              {(() => {
                try {
                  return "درخواست پرستار";
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "\u06a9\u0644\u06cc\u0646\u06cc\u06a9";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          ) : (
            <React.Fragment>
              {(() => {
                try {
                  return $props.item.name;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "\u06a9\u0644\u06cc\u0646\u06cc\u06a9";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          )}
        </div>
        <div
          className={classNames("all", "__wab_text", sty.text___6GhB, {
            [sty.texthome___6GhBvEsIk]: hasVariant($state, "home", "home")
          })}
        >
          {hasVariant($state, "home", "home") ? (
            <React.Fragment>
              {(() => {
                try {
                  return "درخواست پرستار";
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "\u06a9\u0644\u06cc\u0646\u06cc\u06a9";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          ) : (
            <React.Fragment>
              {(() => {
                try {
                  return $props.item.center_name;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "\u06a9\u0644\u06cc\u0646\u06cc\u06a9";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          )}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "svg"],
  img: ["img"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof PlasmicImg__;
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicItemStaffs2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicItemStaffs2__VariantsArgs;
    args?: PlasmicItemStaffs2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicItemStaffs2__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicItemStaffs2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicItemStaffs2__ArgProps,
          internalVariantPropNames: PlasmicItemStaffs2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicItemStaffs2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicItemStaffs2";
  } else {
    func.displayName = `PlasmicItemStaffs2.${nodeName}`;
  }
  return func;
}

export const PlasmicItemStaffs2 = Object.assign(
  // Top-level PlasmicItemStaffs2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicItemStaffs2
    internalVariantProps: PlasmicItemStaffs2__VariantProps,
    internalArgProps: PlasmicItemStaffs2__ArgProps
  }
);

export default PlasmicItemStaffs2;
/* prettier-ignore-end */
