/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qARqpE4p5tZmJuNxFbTaPz
// Component: V2In34aoYVht

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Dialog } from "@plasmicpkgs/radix-ui";
import Button2 from "../../Button2"; // plasmic-import: SlKtguGGSfon/component
import { DialogContent } from "@plasmicpkgs/radix-ui";
import { DialogTitle } from "@plasmicpkgs/radix-ui";
import RadioGroup from "../../RadioGroup"; // plasmic-import: HKDTSu47OrEH/component
import Radio from "../../Radio"; // plasmic-import: 4jWqJWAaH2_L/component
import { DialogClose } from "@plasmicpkgs/radix-ui";
import { _useGlobalVariants } from "../website_starter/plasmic"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectModule
import { _useStyleTokens } from "../website_starter/PlasmicStyleTokensProvider"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../website_starter/plasmic.module.css"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectcss
import sty from "./PlasmicSort.module.css"; // plasmic-import: V2In34aoYVht/css

import ChevronRightIcon from "./icons/PlasmicIcon__ChevronRight"; // plasmic-import: asThzEchEMNJ/icon
import ChevronLeftIcon from "./icons/PlasmicIcon__ChevronLeft"; // plasmic-import: vQC4_6sr1Yuo/icon
import XIcon from "./icons/PlasmicIcon__X"; // plasmic-import: YuRnfxQGHRim/icon

createPlasmicElementProxy;

export type PlasmicSort__VariantMembers = {
  fullpage: "fullpage";
  nopadding: "nopadding";
};
export type PlasmicSort__VariantsArgs = {
  fullpage?: SingleBooleanChoiceArg<"fullpage">;
  nopadding?: SingleBooleanChoiceArg<"nopadding">;
};
type VariantPropType = keyof PlasmicSort__VariantsArgs;
export const PlasmicSort__VariantProps = new Array<VariantPropType>(
  "fullpage",
  "nopadding"
);

export type PlasmicSort__ArgsType = {
  opendialog?: boolean;
  onOpendialogChange?: (val: string) => void;
  radioGroupValue?: any;
  onRadioGroupValueChange?: (val: any) => void;
  item?: any;
  onItemChange?: (val: string) => void;
};
type ArgPropType = keyof PlasmicSort__ArgsType;
export const PlasmicSort__ArgProps = new Array<ArgPropType>(
  "opendialog",
  "onOpendialogChange",
  "radioGroupValue",
  "onRadioGroupValueChange",
  "item",
  "onItemChange"
);

export type PlasmicSort__OverridesType = {
  dialog3?: Flex__<typeof Dialog>;
  button3?: Flex__<typeof Button2>;
  dialogContent?: Flex__<typeof DialogContent>;
  dialogTitle?: Flex__<typeof DialogTitle>;
  radioGroup?: Flex__<typeof RadioGroup>;
  freeBox?: Flex__<"div">;
  radio?: Flex__<typeof Radio>;
  dialogClose?: Flex__<typeof DialogClose>;
};

export interface DefaultSortProps {
  opendialog?: boolean;
  onOpendialogChange?: (val: string) => void;
  radioGroupValue?: any;
  onRadioGroupValueChange?: (val: any) => void;
  item?: any;
  onItemChange?: (val: string) => void;
  fullpage?: SingleBooleanChoiceArg<"fullpage">;
  nopadding?: SingleBooleanChoiceArg<"nopadding">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSort__RenderFunc(props: {
  variants: PlasmicSort__VariantsArgs;
  args: PlasmicSort__ArgsType;
  overrides: PlasmicSort__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "dialog3.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $state.opendialog;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "opendialog",
        type: "writable",
        variableType: "boolean",

        valueProp: "opendialog",
        onChangeProp: "onOpendialogChange"
      },
      {
        path: "button3.color",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "button3.load",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "button3.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "fullpage",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.fullpage
      },
      {
        path: "nopadding",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.nopadding
      },
      {
        path: "radioGroup.value",
        type: "writable",
        variableType: "array",

        valueProp: "radioGroupValue",
        onChangeProp: "onRadioGroupValueChange"
      },
      {
        path: "item",
        type: "writable",
        variableType: "array",

        valueProp: "item",
        onChangeProp: "onItemChange"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <Dialog
      data-plasmic-name={"dialog3"}
      data-plasmic-override={overrides.dialog3}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.dialog3,
        {
          [sty.dialog3fullpage]: hasVariant($state, "fullpage", "fullpage"),
          [sty.dialog3nopadding]: hasVariant($state, "nopadding", "nopadding")
        }
      )}
      defaultOpen={(() => {
        try {
          return $state.opendialog;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return undefined;
          }
          throw e;
        }
      })()}
      onOpenChange={async (...eventArgs: any) => {
        generateStateOnChangeProp($state, ["dialog3", "open"]).apply(
          null,
          eventArgs
        );

        (async open => {
          const $steps = {};

          $steps["updateOpendialog"] = true
            ? (() => {
                const actionArgs = {
                  variable: {
                    objRoot: $state,
                    variablePath: ["opendialog"]
                  },
                  operation: 4
                };
                return (({ variable, value, startIndex, deleteCount }) => {
                  if (!variable) {
                    return;
                  }
                  const { objRoot, variablePath } = variable;

                  const oldValue = $stateGet(objRoot, variablePath);
                  $stateSet(objRoot, variablePath, !oldValue);
                  return !oldValue;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateOpendialog"] != null &&
            typeof $steps["updateOpendialog"] === "object" &&
            typeof $steps["updateOpendialog"].then === "function"
          ) {
            $steps["updateOpendialog"] = await $steps["updateOpendialog"];
          }
        }).apply(null, eventArgs);
      }}
      open={generateStateValueProp($state, ["dialog3", "open"])}
      overlayClassName={classNames({
        [sty["pcls_Lcujj3dcxInB"]]: true,
        [sty["pcls_kL2NX-kIh2BI"]]: hasVariant(
          globalVariants,
          "screen",
          "mobileOnly"
        ),
        [sty["pcls_wczJMcyYFPkm"]]: hasVariant($state, "fullpage", "fullpage")
      })}
      themeResetClass={classNames(
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames
      )}
      triggerSlot={
        <Button2
          data-plasmic-name={"button3"}
          data-plasmic-override={overrides.button3}
          className={classNames("__wab_instance", sty.button3)}
          color={generateStateValueProp($state, ["button3", "color"])}
          endIcon={
            <ChevronLeftIcon
              className={classNames(projectcss.all, sty.svg__dex5B)}
              role={"img"}
            />
          }
          load={generateStateValueProp($state, ["button3", "load"])}
          loading={generateStateValueProp($state, ["button3", "loading"])}
          onColorChange={async (...eventArgs: any) => {
            ((...eventArgs) => {
              generateStateOnChangeProp($state, ["button3", "color"])(
                eventArgs[0]
              );
            }).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          onLoadChange={async (...eventArgs: any) => {
            ((...eventArgs) => {
              generateStateOnChangeProp($state, ["button3", "load"])(
                eventArgs[0]
              );
            }).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          onLoadingChange={async (...eventArgs: any) => {
            ((...eventArgs) => {
              generateStateOnChangeProp($state, ["button3", "loading"])(
                eventArgs[0]
              );
            }).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          startIcon={
            <ChevronRightIcon
              className={classNames(projectcss.all, sty.svg__rM39U)}
              role={"img"}
            />
          }
          submitsForm={false}
        />
      }
    >
      <DialogContent
        data-plasmic-name={"dialogContent"}
        data-plasmic-override={overrides.dialogContent}
        className={classNames("__wab_instance", sty.dialogContent, {
          [sty.dialogContentfullpage]: hasVariant(
            $state,
            "fullpage",
            "fullpage"
          ),
          [sty.dialogContentnopadding]: hasVariant(
            $state,
            "nopadding",
            "nopadding"
          )
        })}
        enterAnimations={
          hasVariant(globalVariants, "screen", "mobileOnly")
            ? ["slide-in-from-bottom"]
            : ["zoom-enter", "fade-in"]
        }
        enterDuration={0.5}
        exitAnimations={
          hasVariant(globalVariants, "screen", "mobileOnly")
            ? ["slide-out-to-bottom"]
            : ["zoom-exit", "fade-out"]
        }
        exitDuration={0.5}
        themeResetClass={classNames(
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          styleTokensClassNames
        )}
      >
        <DialogTitle
          data-plasmic-name={"dialogTitle"}
          data-plasmic-override={overrides.dialogTitle}
          className={classNames("__wab_instance", sty.dialogTitle)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__aqXkM
            )}
          >
            {"Sheet title"}
          </div>
        </DialogTitle>
        <RadioGroup
          data-plasmic-name={"radioGroup"}
          data-plasmic-override={overrides.radioGroup}
          className={classNames("__wab_instance", sty.radioGroup)}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___8Oytd
              )}
            >
              {
                "\u0645\u0631\u062a\u0628 \u0633\u0627\u0632\u06cc \u0628\u0631 \u0627\u0633\u0627\u0633:"
              }
            </div>
          }
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["radioGroup", "value"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          options={
            <div
              data-plasmic-name={"freeBox"}
              data-plasmic-override={overrides.freeBox}
              className={classNames(projectcss.all, sty.freeBox)}
            >
              {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                (() => {
                  try {
                    return [
                      {
                        label: "پیش‌فرض",
                        value: null
                      },
                      {
                        label: "بیشترین امتیاز",
                        value: "highest_rate"
                      },
                      {
                        label: "کم‌هزینه‌ترین",
                        value: "lowest_price"
                      },
                      {
                        label: "محبوب‌ترین",
                        value: "most_popular"
                      }
                    ];
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return [];
                    }
                    throw e;
                  }
                })()
              ).map((__plasmic_item_0, __plasmic_idx_0) => {
                const currentItem = __plasmic_item_0;
                const currentIndex = __plasmic_idx_0;
                return (
                  <Radio
                    data-plasmic-name={"radio"}
                    data-plasmic-override={overrides.radio}
                    className={classNames("__wab_instance", sty.radio)}
                    key={currentIndex}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___54INl
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return currentItem.label;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Option 1";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    }
                    value={(() => {
                      try {
                        return currentItem.value;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                  />
                );
              })}
            </div>
          }
          value={generateStateValueProp($state, ["radioGroup", "value"])}
        />

        <DialogClose
          data-plasmic-name={"dialogClose"}
          data-plasmic-override={overrides.dialogClose}
          className={classNames("__wab_instance", sty.dialogClose)}
        >
          <XIcon
            className={classNames(projectcss.all, sty.svg__cGmDm)}
            role={"img"}
          />
        </DialogClose>
      </DialogContent>
    </Dialog>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  dialog3: [
    "dialog3",
    "button3",
    "dialogContent",
    "dialogTitle",
    "radioGroup",
    "freeBox",
    "radio",
    "dialogClose"
  ],
  button3: ["button3"],
  dialogContent: [
    "dialogContent",
    "dialogTitle",
    "radioGroup",
    "freeBox",
    "radio",
    "dialogClose"
  ],
  dialogTitle: ["dialogTitle"],
  radioGroup: ["radioGroup", "freeBox", "radio"],
  freeBox: ["freeBox", "radio"],
  radio: ["radio"],
  dialogClose: ["dialogClose"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  dialog3: typeof Dialog;
  button3: typeof Button2;
  dialogContent: typeof DialogContent;
  dialogTitle: typeof DialogTitle;
  radioGroup: typeof RadioGroup;
  freeBox: "div";
  radio: typeof Radio;
  dialogClose: typeof DialogClose;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSort__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSort__VariantsArgs;
    args?: PlasmicSort__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSort__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSort__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSort__ArgProps,
          internalVariantPropNames: PlasmicSort__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSort__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "dialog3") {
    func.displayName = "PlasmicSort";
  } else {
    func.displayName = `PlasmicSort.${nodeName}`;
  }
  return func;
}

export const PlasmicSort = Object.assign(
  // Top-level PlasmicSort renders the root element
  makeNodeComponent("dialog3"),
  {
    // Helper components rendering sub-elements
    button3: makeNodeComponent("button3"),
    dialogContent: makeNodeComponent("dialogContent"),
    dialogTitle: makeNodeComponent("dialogTitle"),
    radioGroup: makeNodeComponent("radioGroup"),
    freeBox: makeNodeComponent("freeBox"),
    radio: makeNodeComponent("radio"),
    dialogClose: makeNodeComponent("dialogClose"),

    // Metadata about props expected for PlasmicSort
    internalVariantProps: PlasmicSort__VariantProps,
    internalArgProps: PlasmicSort__ArgProps
  }
);

export default PlasmicSort;
/* prettier-ignore-end */
