/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qARqpE4p5tZmJuNxFbTaPz
// Component: 4UaemkVPEyQ4

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import StatusIcon from "../../StatusIcon"; // plasmic-import: zJ2RueI-cLbg/component
import UploudeTime from "../../UploudeTime"; // plasmic-import: IxvwO5AMD5ex/component
import Button from "../../Button"; // plasmic-import: 2MRRFY7jUAge/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicReservationItem.module.css"; // plasmic-import: 4UaemkVPEyQ4/css

import CheckIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__Check"; // plasmic-import: DtxnCWLfceEB/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: cDVOBX0F9d9g/icon

createPlasmicElementProxy;

export type PlasmicReservationItem__VariantMembers = {
  open: "open";
};
export type PlasmicReservationItem__VariantsArgs = {
  open?: SingleBooleanChoiceArg<"open">;
};
type VariantPropType = keyof PlasmicReservationItem__VariantsArgs;
export const PlasmicReservationItem__VariantProps = new Array<VariantPropType>(
  "open"
);

export type PlasmicReservationItem__ArgsType = {
  user?: any;
  currentItem?: any;
  onOpenChange?: (val: any) => void;
};
type ArgPropType = keyof PlasmicReservationItem__ArgsType;
export const PlasmicReservationItem__ArgProps = new Array<ArgPropType>(
  "user",
  "currentItem",
  "onOpenChange"
);

export type PlasmicReservationItem__OverridesType = {
  root?: Flex__<"div">;
  statusIcon?: Flex__<typeof StatusIcon>;
  uploudeTime?: Flex__<typeof UploudeTime>;
  add?: Flex__<typeof Button>;
};

export interface DefaultReservationItemProps {
  user?: any;
  currentItem?: any;
  onOpenChange?: (val: any) => void;
  open?: SingleBooleanChoiceArg<"open">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicReservationItem__RenderFunc(props: {
  variants: PlasmicReservationItem__VariantsArgs;
  args: PlasmicReservationItem__ArgsType;
  overrides: PlasmicReservationItem__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          user: {}
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "open",
        type: "writable",
        variableType: "variant",

        valueProp: "open",
        onChangeProp: "onOpenChange"
      },
      {
        path: "add.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_qARqpE4p5tZmJuNxFbTaPz",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        className={classNames("all", sty.freeBox__xiDa9)}
        onClick={async event => {
          const $steps = {};

          $steps["updateOpen"] = true
            ? (() => {
                const actionArgs = {
                  vgroup: "open",
                  operation: 2,
                  value: "open"
                };
                return (({ vgroup, value }) => {
                  if (typeof value === "string") {
                    value = [value];
                  }

                  const oldValue = $stateGet($state, vgroup);
                  $stateSet($state, vgroup, !oldValue);
                  return !oldValue;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateOpen"] != null &&
            typeof $steps["updateOpen"] === "object" &&
            typeof $steps["updateOpen"].then === "function"
          ) {
            $steps["updateOpen"] = await $steps["updateOpen"];
          }
        }}
      >
        <StatusIcon
          data-plasmic-name={"statusIcon"}
          data-plasmic-override={overrides.statusIcon}
          className={classNames("__wab_instance", sty.statusIcon)}
          status={(() => {
            try {
              return $props.currentItem.status;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()}
        />

        <div className={classNames("all", sty.freeBox__vCUW)}>
          <div className={classNames("all", "__wab_text", sty.text__wnq7Y)}>
            <React.Fragment>{`${$props.currentItem.name} (${$props.currentItem.service_name})`}</React.Fragment>
          </div>
          <UploudeTime
            data-plasmic-name={"uploudeTime"}
            data-plasmic-override={overrides.uploudeTime}
            className={classNames("__wab_instance", sty.uploudeTime)}
            posttime={(() => {
              function addTime(dateString, addHours = 0, addMinutes = 0) {
                if (!dateString) return null;
                const date = new Date(dateString.replace(" ", "T"));
                if (!date) return null;
                date.setMinutes(
                  date.getMinutes() + (addHours * 60 + addMinutes)
                );
                return {
                  year: date.getFullYear(),
                  month: date.getMonth() + 1,
                  day: date.getDate(),
                  hour: date.getHours(),
                  minute: date.getMinutes(),
                  second: date.getSeconds()
                };
              }
              const newCreatedAt = addTime($props?.currentItem?.start_time);
              return newCreatedAt;
            })()}
          />
        </div>
        <Button
          data-plasmic-name={"add"}
          data-plasmic-override={overrides.add}
          className={classNames("__wab_instance", sty.add)}
          color={"success"}
          iconStart={true}
          label={
            <div className={classNames("all", "__wab_text", sty.text__pPgHu)}>
              {"\u062a\u0627\u06cc\u06cc\u062f \u0631\u0632\u0631\u0648"}
            </div>
          }
          loading={generateStateValueProp($state, ["add", "loading"])}
          onLoadingChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["add", "loading"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          start={
            <CheckIcon
              className={classNames("all", sty.svg__irS4T)}
              role={"img"}
            />
          }
        />

        <ChevronDownIcon
          className={classNames("all", sty.svg__dwid7, {
            [sty.svgopen__dwid7Lb9Mw]: hasVariant($state, "open", "open")
          })}
          role={"img"}
        />
      </div>
      {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
        (() => {
          try {
            return $props.user[0].subcategories;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return [];
            }
            throw e;
          }
        })()
      ).map((__plasmic_item_0, __plasmic_idx_0) => {
        const currentItem = __plasmic_item_0;
        const currentIndex = __plasmic_idx_0;
        return (
          <div
            className={classNames("all", sty.freeBox__g5Ljn, {
              [sty.freeBoxopen__g5LjnLb9Mw]: hasVariant($state, "open", "open")
            })}
            key={currentIndex}
          >
            <div className={classNames("all", "__wab_text", sty.text__jQxhK)}>
              <React.Fragment>{currentItem.name}</React.Fragment>
            </div>
            <div className={classNames("all", "__wab_text", sty.text__tfY45)}>
              <React.Fragment>{currentItem.description}</React.Fragment>
            </div>
          </div>
        );
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "statusIcon", "uploudeTime", "add"],
  statusIcon: ["statusIcon"],
  uploudeTime: ["uploudeTime"],
  add: ["add"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  statusIcon: typeof StatusIcon;
  uploudeTime: typeof UploudeTime;
  add: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicReservationItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicReservationItem__VariantsArgs;
    args?: PlasmicReservationItem__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicReservationItem__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicReservationItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicReservationItem__ArgProps,
          internalVariantPropNames: PlasmicReservationItem__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicReservationItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicReservationItem";
  } else {
    func.displayName = `PlasmicReservationItem.${nodeName}`;
  }
  return func;
}

export const PlasmicReservationItem = Object.assign(
  // Top-level PlasmicReservationItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    statusIcon: makeNodeComponent("statusIcon"),
    uploudeTime: makeNodeComponent("uploudeTime"),
    add: makeNodeComponent("add"),

    // Metadata about props expected for PlasmicReservationItem
    internalVariantProps: PlasmicReservationItem__VariantProps,
    internalArgProps: PlasmicReservationItem__ArgProps
  }
);

export default PlasmicReservationItem;
/* prettier-ignore-end */
