/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qARqpE4p5tZmJuNxFbTaPz
// Component: D1_7W8_3U14A

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import UploudeTime from "../../UploudeTime"; // plasmic-import: IxvwO5AMD5ex/component
import { TextCollapse } from "@/components/TextCollapse"; // plasmic-import: 4siMWQuiaqGI/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicNotifBox.module.css"; // plasmic-import: D1_7W8_3U14A/css

import BrandTelegramIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__BrandTelegram"; // plasmic-import: 4E611EcCApzn/icon
import Icon76Icon from "./icons/PlasmicIcon__Icon76"; // plasmic-import: PNmvwHPTSPVF/icon
import Icon32Icon from "./icons/PlasmicIcon__Icon32"; // plasmic-import: hVogcrNM7Ss9/icon

createPlasmicElementProxy;

export type PlasmicNotifBox__VariantMembers = {
  open: "open";
  seen: "seen";
};
export type PlasmicNotifBox__VariantsArgs = {
  open?: SingleBooleanChoiceArg<"open">;
  seen?: SingleBooleanChoiceArg<"seen">;
};
type VariantPropType = keyof PlasmicNotifBox__VariantsArgs;
export const PlasmicNotifBox__VariantProps = new Array<VariantPropType>(
  "open",
  "seen"
);

export type PlasmicNotifBox__ArgsType = {
  onClick?: (event: any) => void;
  q?: string;
  time?: string;
  action?: string;
  slot?: React.ReactNode;
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicNotifBox__ArgsType;
export const PlasmicNotifBox__ArgProps = new Array<ArgPropType>(
  "onClick",
  "q",
  "time",
  "action",
  "slot",
  "children"
);

export type PlasmicNotifBox__OverridesType = {
  root?: Flex__<"div">;
  uploudeTime?: Flex__<typeof UploudeTime>;
  textCollapse?: Flex__<typeof TextCollapse>;
  text?: Flex__<"div">;
};

export interface DefaultNotifBoxProps {
  onClick?: (event: any) => void;
  q?: string;
  time?: string;
  action?: string;
  slot?: React.ReactNode;
  children?: React.ReactNode;
  open?: SingleBooleanChoiceArg<"open">;
  seen?: SingleBooleanChoiceArg<"seen">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNotifBox__RenderFunc(props: {
  variants: PlasmicNotifBox__VariantsArgs;
  args: PlasmicNotifBox__ArgsType;
  overrides: PlasmicNotifBox__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "open",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.open
      },
      {
        path: "seen",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.seen
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_qARqpE4p5tZmJuNxFbTaPz",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootopen]: hasVariant($state, "open", "open"),
          [sty.rootseen]: hasVariant($state, "seen", "seen")
        }
      )}
    >
      <div
        className={classNames("all", sty.freeBox__wV4I, {
          [sty.freeBoxopen__wV4I6KqS6]: hasVariant($state, "open", "open")
        })}
        onClick={async event => {
          const $steps = {};

          $steps["updateOpen"] = true
            ? (() => {
                const actionArgs = {
                  vgroup: "open",
                  operation: 2,
                  value: "open"
                };
                return (({ vgroup, value }) => {
                  if (typeof value === "string") {
                    value = [value];
                  }

                  const oldValue = $stateGet($state, vgroup);
                  $stateSet($state, vgroup, !oldValue);
                  return !oldValue;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateOpen"] != null &&
            typeof $steps["updateOpen"] === "object" &&
            typeof $steps["updateOpen"].then === "function"
          ) {
            $steps["updateOpen"] = await $steps["updateOpen"];
          }
        }}
      >
        {renderPlasmicSlot({
          defaultContents: (
            <BrandTelegramIcon
              className={classNames("all", sty.svg__kgRat)}
              role={"img"}
            />
          ),

          value: args.slot
        })}
        <div
          className={classNames("all", sty.freeBox__wAjHi, {
            [sty.freeBoxopen__wAjHi6KqS6]: hasVariant($state, "open", "open")
          })}
        >
          <div className={classNames("all", sty.freeBox__vqK68)}>
            {renderPlasmicSlot({
              defaultContents:
                "\u067e\u0634\u062a\u06cc\u0628\u0627\u0646\u06cc \u062a\u0644\u06af\u0631\u0627\u0645\u06cc",
              value: args.children,
              className: classNames(sty.slotTargetChildren)
            })}
            <UploudeTime
              data-plasmic-name={"uploudeTime"}
              data-plasmic-override={overrides.uploudeTime}
              className={classNames("__wab_instance", sty.uploudeTime)}
              posttime={$props.time}
            />
          </div>
          <TextCollapse
            data-plasmic-name={"textCollapse"}
            data-plasmic-override={overrides.textCollapse}
            className={classNames("__wab_instance", sty.textCollapse, {
              [sty.textCollapseopen]: hasVariant($state, "open", "open")
            })}
            enableToggle={false}
            maxLines={1}
            text={(() => {
              try {
                return $props.q;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
          />
        </div>
        <Icon76Icon
          className={classNames("all", sty.svg__aqPl, {
            [sty.svgopen__aqPl6KqS6]: hasVariant($state, "open", "open")
          })}
          role={"img"}
        />
      </div>
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames("all", "__wab_text", sty.text, {
          [sty.textopen]: hasVariant($state, "open", "open")
        })}
      >
        <React.Fragment>{$props.q}</React.Fragment>
      </div>
      <Icon32Icon
        className={classNames("all", sty.svg__b7XlJ, {
          [sty.svgseen__b7XlJjmYVk]: hasVariant($state, "seen", "seen")
        })}
        role={"img"}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "uploudeTime", "textCollapse", "text"],
  uploudeTime: ["uploudeTime"],
  textCollapse: ["textCollapse"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  uploudeTime: typeof UploudeTime;
  textCollapse: typeof TextCollapse;
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNotifBox__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNotifBox__VariantsArgs;
    args?: PlasmicNotifBox__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNotifBox__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNotifBox__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNotifBox__ArgProps,
          internalVariantPropNames: PlasmicNotifBox__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNotifBox__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNotifBox";
  } else {
    func.displayName = `PlasmicNotifBox.${nodeName}`;
  }
  return func;
}

export const PlasmicNotifBox = Object.assign(
  // Top-level PlasmicNotifBox renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    uploudeTime: makeNodeComponent("uploudeTime"),
    textCollapse: makeNodeComponent("textCollapse"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicNotifBox
    internalVariantProps: PlasmicNotifBox__VariantProps,
    internalArgProps: PlasmicNotifBox__ArgProps
  }
);

export default PlasmicNotifBox;
/* prettier-ignore-end */
