/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qARqpE4p5tZmJuNxFbTaPz
// Component: k7RSAEFr4xx-

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Select from "../../Select"; // plasmic-import: IQ4yTzxYcpjO/component
import MenuItem from "../../MenuItem"; // plasmic-import: fC_9RAtGrwae/component
import DateInput from "../../DateInput"; // plasmic-import: 8LUOC3uVttVT/component
import TimeInput from "../../TimeInput"; // plasmic-import: DjbuB4u8rb_D/component
import TextAreaInput from "../../TextAreaInput"; // plasmic-import: qqmK9B2Ozci4/component
import AddressDialog from "../../AddressDialog"; // plasmic-import: 2oWI7rmW5yjT/component
import Check from "../../Check"; // plasmic-import: jHhGioxaI9lI/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicAnswersUser.module.css"; // plasmic-import: k7RSAEFr4xx-/css

createPlasmicElementProxy;

export type PlasmicAnswersUser__VariantMembers = {};
export type PlasmicAnswersUser__VariantsArgs = {};
type VariantPropType = keyof PlasmicAnswersUser__VariantsArgs;
export const PlasmicAnswersUser__VariantProps = new Array<VariantPropType>();

export type PlasmicAnswersUser__ArgsType = {
  token?: string;
  currentItem?: any;
  answers?: string;
  onAnswersChange?: (val: string) => void;
  data?: any;
  onDataChange?: (val: string) => void;
  addressDialogAddUser?: () => void;
};
type ArgPropType = keyof PlasmicAnswersUser__ArgsType;
export const PlasmicAnswersUser__ArgProps = new Array<ArgPropType>(
  "token",
  "currentItem",
  "answers",
  "onAnswersChange",
  "data",
  "onDataChange",
  "addressDialogAddUser"
);

export type PlasmicAnswersUser__OverridesType = {
  root?: Flex__<"div">;
  select?: Flex__<typeof Select>;
  menuItem?: Flex__<typeof MenuItem>;
  dateInput?: Flex__<typeof DateInput>;
  timeInput?: Flex__<typeof TimeInput>;
  textAreaInput?: Flex__<typeof TextAreaInput>;
  addressDialog?: Flex__<typeof AddressDialog>;
  check?: Flex__<typeof Check>;
};

export interface DefaultAnswersUserProps {
  token?: string;
  currentItem?: any;
  answers?: string;
  onAnswersChange?: (val: string) => void;
  data?: any;
  onDataChange?: (val: string) => void;
  addressDialogAddUser?: () => void;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAnswersUser__RenderFunc(props: {
  variants: PlasmicAnswersUser__VariantsArgs;
  args: PlasmicAnswersUser__ArgsType;
  overrides: PlasmicAnswersUser__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          token:
            "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiZXhwaXJlIjoxNzY0NTA2MjczfQ.A6wRqW0jMYVg_rZ4OMZ5oXrcOVwKq3BG4i_wmvKf_8A"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "select.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "select.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "textAreaInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "addressDialog.subcategories",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ({})
      },
      {
        path: "addressDialog.refresh",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "check.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "answers",
        type: "writable",
        variableType: "text",

        valueProp: "answers",
        onChangeProp: "onAnswersChange"
      },
      {
        path: "dateInput.date",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ({})
      },
      {
        path: "timeInput.time",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ({})
      },
      {
        path: "addressDialog.selected",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ({})
      },
      {
        path: "data",
        type: "writable",
        variableType: "object",

        valueProp: "data",
        onChangeProp: "onDataChange"
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_qARqpE4p5tZmJuNxFbTaPz",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
    >
      {(() => {
        try {
          return $props.currentItem.type != "checkbox";
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <div className={classNames("all", sty.freeBox__setP)}>
          <div className={classNames("all", "__wab_text", sty.text__wm38M)}>
            <React.Fragment>{$props.currentItem.question_text}</React.Fragment>
          </div>
          {(() => {
            try {
              return $props.currentItem.is_required;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div className={classNames("all", "__wab_text", sty.text__dp4B)}>
              {"*"}
            </div>
          ) : null}
        </div>
      ) : null}
      {(() => {
        try {
          return $props.currentItem.type == "single_choice";
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <div className={classNames("all", sty.freeBox__a3MbV)}>
          <Select
            data-plasmic-name={"select"}
            data-plasmic-override={overrides.select}
            className={classNames("__wab_instance", sty.select)}
            description={"Description..."}
            isOpen={generateStateValueProp($state, ["select", "isOpen"])}
            items={(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
              (() => {
                try {
                  return JSON.parse($props.currentItem?.options || "[]");
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [];
                  }
                  throw e;
                }
              })()
            ).map((__plasmic_item_0, __plasmic_idx_0) => {
              const currentItem = __plasmic_item_0;
              const currentIndex = __plasmic_idx_0;
              return (
                <MenuItem
                  data-plasmic-name={"menuItem"}
                  data-plasmic-override={overrides.menuItem}
                  key={currentIndex}
                  label={(() => {
                    try {
                      return currentItem;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  value={(() => {
                    try {
                      return currentItem;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                />
              );
            })}
            label={"Label"}
            onChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["select", "value"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }

              (async val => {
                const $steps = {};

                $steps["updateAnswers"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["answers"]
                        },
                        operation: 0,
                        value: $state.select.value
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateAnswers"] != null &&
                  typeof $steps["updateAnswers"] === "object" &&
                  typeof $steps["updateAnswers"].then === "function"
                ) {
                  $steps["updateAnswers"] = await $steps["updateAnswers"];
                }
              }).apply(null, eventArgs);
            }}
            onOpenChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["select", "isOpen"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            placeholder={
              "\u0644\u0637\u0641\u0627 \u06af\u0632\u06cc\u0646\u0647 \u0645\u0648\u0631\u062f \u0646\u0638\u0631 \u0631\u0627 \u0627\u0646\u062a\u062e\u0627\u0628 \u06a9\u0646\u06cc\u062f"
            }
            showLabel={false}
            type={"lineBoxDark"}
            value={generateStateValueProp($state, ["select", "value"])}
          />
        </div>
      ) : null}
      {(() => {
        try {
          return $props.currentItem.type == "date";
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <DateInput
          data-plasmic-name={"dateInput"}
          data-plasmic-override={overrides.dateInput}
          className={classNames("__wab_instance", sty.dateInput)}
          date={generateStateValueProp($state, ["dateInput", "date"])}
          onDateChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["dateInput", "date"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }

            (async val => {
              const $steps = {};

              $steps["updateAnswers"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["answers"]
                      },
                      operation: 0,
                      value: $state.dateInput.date
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateAnswers"] != null &&
                typeof $steps["updateAnswers"] === "object" &&
                typeof $steps["updateAnswers"].then === "function"
              ) {
                $steps["updateAnswers"] = await $steps["updateAnswers"];
              }
            }).apply(null, eventArgs);
          }}
        />
      ) : null}
      {(() => {
        try {
          return $props.currentItem.type == "time";
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <TimeInput
          data-plasmic-name={"timeInput"}
          data-plasmic-override={overrides.timeInput}
          className={classNames("__wab_instance", sty.timeInput)}
          onTimeChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["timeInput", "time"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }

            (async val => {
              const $steps = {};

              $steps["updateAnswers"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["answers"]
                      },
                      operation: 0,
                      value: $state.timeInput.time
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateAnswers"] != null &&
                typeof $steps["updateAnswers"] === "object" &&
                typeof $steps["updateAnswers"].then === "function"
              ) {
                $steps["updateAnswers"] = await $steps["updateAnswers"];
              }
            }).apply(null, eventArgs);
          }}
          time={generateStateValueProp($state, ["timeInput", "time"])}
        />
      ) : null}
      {(() => {
        try {
          return $props.currentItem.type == "textarea";
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <TextAreaInput
          data-plasmic-name={"textAreaInput"}
          data-plasmic-override={overrides.textAreaInput}
          className={classNames("__wab_instance", sty.textAreaInput)}
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["textAreaInput", "value"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }

            (async val => {
              const $steps = {};

              $steps["updateAnswers"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["answers"]
                      },
                      operation: 0,
                      value: $state.textAreaInput.value
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateAnswers"] != null &&
                typeof $steps["updateAnswers"] === "object" &&
                typeof $steps["updateAnswers"].then === "function"
              ) {
                $steps["updateAnswers"] = await $steps["updateAnswers"];
              }
            }).apply(null, eventArgs);
          }}
          placeholder={"\u062a\u0648\u0636\u06cc\u062d\u0627\u062a "}
          type={"darkOutline"}
          value={generateStateValueProp($state, ["textAreaInput", "value"])}
        />
      ) : null}
      {(() => {
        try {
          return $props.currentItem.type == "address";
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <AddressDialog
          data-plasmic-name={"addressDialog"}
          data-plasmic-override={overrides.addressDialog}
          addUser={args.addressDialogAddUser}
          className={classNames("__wab_instance", sty.addressDialog)}
          onRefreshChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "addressDialog",
              "refresh"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          onSelectedChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "addressDialog",
              "selected"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }

            (async val => {
              const $steps = {};

              $steps["updateAnswers"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["answers"]
                      },
                      operation: 0,
                      value: $state.addressDialog.selected
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateAnswers"] != null &&
                typeof $steps["updateAnswers"] === "object" &&
                typeof $steps["updateAnswers"].then === "function"
              ) {
                $steps["updateAnswers"] = await $steps["updateAnswers"];
              }
            }).apply(null, eventArgs);
          }}
          onSubcategoriesChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "addressDialog",
              "subcategories"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          refresh={generateStateValueProp($state, ["addressDialog", "refresh"])}
          selected={generateStateValueProp($state, [
            "addressDialog",
            "selected"
          ])}
          subcategories={generateStateValueProp($state, [
            "addressDialog",
            "subcategories"
          ])}
          token={(() => {
            try {
              return $props.token;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
        />
      ) : null}
      {(() => {
        try {
          return $props.currentItem.type == "checkbox";
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <Check
          data-plasmic-name={"check"}
          data-plasmic-override={overrides.check}
          className={classNames("__wab_instance", sty.check)}
          isSelected={generateStateValueProp($state, ["check", "isSelected"])}
          label={
            <React.Fragment>{$props.currentItem.question_text}</React.Fragment>
          }
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["check", "isSelected"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }

            (async val => {
              const $steps = {};

              $steps["updateAnswers"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["answers"]
                      },
                      operation: 0,
                      value: $state.check.isSelected
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateAnswers"] != null &&
                typeof $steps["updateAnswers"] === "object" &&
                typeof $steps["updateAnswers"].then === "function"
              ) {
                $steps["updateAnswers"] = await $steps["updateAnswers"];
              }
            }).apply(null, eventArgs);
          }}
        />
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "select",
    "menuItem",
    "dateInput",
    "timeInput",
    "textAreaInput",
    "addressDialog",
    "check"
  ],
  select: ["select", "menuItem"],
  menuItem: ["menuItem"],
  dateInput: ["dateInput"],
  timeInput: ["timeInput"],
  textAreaInput: ["textAreaInput"],
  addressDialog: ["addressDialog"],
  check: ["check"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  select: typeof Select;
  menuItem: typeof MenuItem;
  dateInput: typeof DateInput;
  timeInput: typeof TimeInput;
  textAreaInput: typeof TextAreaInput;
  addressDialog: typeof AddressDialog;
  check: typeof Check;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAnswersUser__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAnswersUser__VariantsArgs;
    args?: PlasmicAnswersUser__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicAnswersUser__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicAnswersUser__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAnswersUser__ArgProps,
          internalVariantPropNames: PlasmicAnswersUser__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAnswersUser__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAnswersUser";
  } else {
    func.displayName = `PlasmicAnswersUser.${nodeName}`;
  }
  return func;
}

export const PlasmicAnswersUser = Object.assign(
  // Top-level PlasmicAnswersUser renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    select: makeNodeComponent("select"),
    menuItem: makeNodeComponent("menuItem"),
    dateInput: makeNodeComponent("dateInput"),
    timeInput: makeNodeComponent("timeInput"),
    textAreaInput: makeNodeComponent("textAreaInput"),
    addressDialog: makeNodeComponent("addressDialog"),
    check: makeNodeComponent("check"),

    // Metadata about props expected for PlasmicAnswersUser
    internalVariantProps: PlasmicAnswersUser__VariantProps,
    internalArgProps: PlasmicAnswersUser__ArgProps
  }
);

export default PlasmicAnswersUser;
/* prettier-ignore-end */
