/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qARqpE4p5tZmJuNxFbTaPz
// Component: DjbuB4u8rb_D

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Dialog from "../../Dialog"; // plasmic-import: AoPc4Hy8St02/component
import { TimePickerCustom } from "@/components/TimePickerCustom"; // plasmic-import: 4tsOFSHTfvZu/codeComponent
import Button from "../../Button"; // plasmic-import: 2MRRFY7jUAge/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicTimeInput.module.css"; // plasmic-import: DjbuB4u8rb_D/css

import ClockIcon from "./icons/PlasmicIcon__Clock"; // plasmic-import: j27xQWkySupk/icon
import Icon11Icon from "./icons/PlasmicIcon__Icon11"; // plasmic-import: TLjQehPXSyaR/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 4RgfxZWAffAT/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: cDVOBX0F9d9g/icon

createPlasmicElementProxy;

export type PlasmicTimeInput__VariantMembers = {
  label: "label";
};
export type PlasmicTimeInput__VariantsArgs = {
  label?: SingleBooleanChoiceArg<"label">;
};
type VariantPropType = keyof PlasmicTimeInput__VariantsArgs;
export const PlasmicTimeInput__VariantProps = new Array<VariantPropType>(
  "label"
);

export type PlasmicTimeInput__ArgsType = {
  time?: any;
  onTimeChange?: (val: string) => void;
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicTimeInput__ArgsType;
export const PlasmicTimeInput__ArgProps = new Array<ArgPropType>(
  "time",
  "onTimeChange",
  "children"
);

export type PlasmicTimeInput__OverridesType = {
  root?: Flex__<"div">;
  dialog?: Flex__<typeof Dialog>;
  timePickerCustom?: Flex__<typeof TimePickerCustom>;
  button3?: Flex__<typeof Button>;
};

export interface DefaultTimeInputProps {
  time?: any;
  onTimeChange?: (val: string) => void;
  children?: React.ReactNode;
  label?: SingleBooleanChoiceArg<"label">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTimeInput__RenderFunc(props: {
  variants: PlasmicTimeInput__VariantsArgs;
  args: PlasmicTimeInput__ArgsType;
  overrides: PlasmicTimeInput__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "dialog.opendialog",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "button3.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "time",
        type: "writable",
        variableType: "object",

        valueProp: "time",
        onChangeProp: "onTimeChange"
      },
      {
        path: "timePickerCustom.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "label",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.label
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_qARqpE4p5tZmJuNxFbTaPz",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root,
        { [sty.rootlabel]: hasVariant($state, "label", "label") }
      )}
    >
      <div className={classNames("all", sty.freeBox__mnPp)}>
        <ClockIcon
          className={classNames("all", sty.svg__nuSw2, {
            [sty.svglabel__nuSw2OaGyf]: hasVariant($state, "label", "label")
          })}
          role={"img"}
        />

        <div
          className={classNames("all", sty.freeBox__eYvYb)}
          onClick={async event => {
            const $steps = {};

            $steps["updateDialogOpendialog"] = true
              ? (() => {
                  const actionArgs = {
                    variable: {
                      objRoot: $state,
                      variablePath: ["dialog", "opendialog"]
                    },
                    operation: 0,
                    value: true
                  };
                  return (({ variable, value, startIndex, deleteCount }) => {
                    if (!variable) {
                      return;
                    }
                    const { objRoot, variablePath } = variable;

                    $stateSet(objRoot, variablePath, value);
                    return value;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateDialogOpendialog"] != null &&
              typeof $steps["updateDialogOpendialog"] === "object" &&
              typeof $steps["updateDialogOpendialog"].then === "function"
            ) {
              $steps["updateDialogOpendialog"] =
                await $steps["updateDialogOpendialog"];
            }
          }}
        >
          {(() => {
            try {
              return !$state.time.hour;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div className={classNames("all", "__wab_text", sty.text__xu0Qs)}>
              <React.Fragment>
                {(() => {
                  try {
                    return "مثال:  12:30";
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "\u0645\u062b\u0627\u0644 1406/5/1";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          ) : null}
          <div
            className={classNames("all", sty.freeBox__j8YGs, {
              [sty.freeBoxlabel__j8YGsOaGyf]: hasVariant(
                $state,
                "label",
                "label"
              )
            })}
          >
            {renderPlasmicSlot({
              defaultContents:
                "\u0633\u0627\u0639\u062a \u0634\u0631\u0648\u0639 \u0628\u0647 \u06a9\u0627\u0631",
              value: args.children,
              className: classNames(sty.slotTargetChildren, {
                [sty.slotTargetChildrenlabel]: hasVariant(
                  $state,
                  "label",
                  "label"
                )
              })
            })}
          </div>
          {(() => {
            try {
              return $state.time.hour;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div className={classNames("all", "__wab_text", sty.text__pk1Q6)}>
              <React.Fragment>
                {(() => {
                  try {
                    return `${String($state.time.minute).padStart(2, "0")} : ${String($state.time.hour).padStart(2, "0")}`;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "\u0645\u062b\u0627\u0644 1406/5/1";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          ) : null}
        </div>
        {(() => {
          try {
            return $state.time.hour;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return true;
            }
            throw e;
          }
        })() ? (
          <Icon11Icon
            className={classNames("all", sty.svg__oVekl)}
            onClick={async event => {
              const $steps = {};

              $steps["runCode"] = true
                ? (() => {
                    const actionArgs = {
                      customFunction: async () => {
                        return ($state.time = {});
                      }
                    };
                    return (({ customFunction }) => {
                      return customFunction();
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runCode"] != null &&
                typeof $steps["runCode"] === "object" &&
                typeof $steps["runCode"].then === "function"
              ) {
                $steps["runCode"] = await $steps["runCode"];
              }
            }}
            role={"img"}
          />
        ) : null}
      </div>
      <Dialog
        data-plasmic-name={"dialog"}
        data-plasmic-override={overrides.dialog}
        className={classNames("__wab_instance", sty.dialog)}
        colorback={"w"}
        onOpendialogChange={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["dialog", "opendialog"]).apply(
            null,
            eventArgs
          );

          if (
            eventArgs.length > 1 &&
            eventArgs[1] &&
            eventArgs[1]._plasmic_state_init_
          ) {
            return;
          }
        }}
        opendialog={generateStateValueProp($state, ["dialog", "opendialog"])}
      >
        <div className={classNames("all", sty.freeBox__re0UP)}>
          <TimePickerCustom
            data-plasmic-name={"timePickerCustom"}
            data-plasmic-override={overrides.timePickerCustom}
            SelectedHour={(() => {
              try {
                return $state.time.hour || 9;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return 9;
                }
                throw e;
              }
            })()}
            SelectedMinute={(() => {
              try {
                return $state.time.minute || 30;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return 30;
                }
                throw e;
              }
            })()}
            className={classNames("__wab_instance", sty.timePickerCustom)}
            onChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, [
                "timePickerCustom",
                "value"
              ]).apply(null, eventArgs);
            }}
            selectedValues={generateStateValueProp($state, [
              "timePickerCustom",
              "value"
            ])}
          />

          <Button
            data-plasmic-name={"button3"}
            data-plasmic-override={overrides.button3}
            className={classNames("__wab_instance", sty.button3)}
            color={"success"}
            label={
              <div className={classNames("all", "__wab_text", sty.text__xCQgA)}>
                {"\u062a\u0627\u06cc\u06cc\u062f"}
              </div>
            }
            loading={generateStateValueProp($state, ["button3", "loading"])}
            onClick={async event => {
              const $steps = {};

              $steps["runCode"] = true
                ? (() => {
                    const actionArgs = {
                      customFunction: async () => {
                        return (() => {
                          $state.time = $state.timePickerCustom.value;
                          return ($state.dialog.opendialog = false);
                        })();
                      }
                    };
                    return (({ customFunction }) => {
                      return customFunction();
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runCode"] != null &&
                typeof $steps["runCode"] === "object" &&
                typeof $steps["runCode"].then === "function"
              ) {
                $steps["runCode"] = await $steps["runCode"];
              }
            }}
            onLoadingChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["button3", "loading"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
          />
        </div>
      </Dialog>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "dialog", "timePickerCustom", "button3"],
  dialog: ["dialog", "timePickerCustom", "button3"],
  timePickerCustom: ["timePickerCustom"],
  button3: ["button3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  dialog: typeof Dialog;
  timePickerCustom: typeof TimePickerCustom;
  button3: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTimeInput__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTimeInput__VariantsArgs;
    args?: PlasmicTimeInput__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicTimeInput__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicTimeInput__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTimeInput__ArgProps,
          internalVariantPropNames: PlasmicTimeInput__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTimeInput__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTimeInput";
  } else {
    func.displayName = `PlasmicTimeInput.${nodeName}`;
  }
  return func;
}

export const PlasmicTimeInput = Object.assign(
  // Top-level PlasmicTimeInput renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dialog: makeNodeComponent("dialog"),
    timePickerCustom: makeNodeComponent("timePickerCustom"),
    button3: makeNodeComponent("button3"),

    // Metadata about props expected for PlasmicTimeInput
    internalVariantProps: PlasmicTimeInput__VariantProps,
    internalArgProps: PlasmicTimeInput__ArgProps
  }
);

export default PlasmicTimeInput;
/* prettier-ignore-end */
