/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qARqpE4p5tZmJuNxFbTaPz

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantstFdSzkuagb1N } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: tFdSZKUAGB1N/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantstFdSzkuagb1N
});
