/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qARqpE4p5tZmJuNxFbTaPz
// Component: Ja5GPSQ1q6Qz

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Dialog } from "@plasmicpkgs/radix-ui";
import Button2 from "../../Button2"; // plasmic-import: SlKtguGGSfon/component
import { DialogContent } from "@plasmicpkgs/radix-ui";
import { DialogTitle } from "@plasmicpkgs/radix-ui";
import Load from "../../Load"; // plasmic-import: giI5l8wTGhHv/component
import { DialogClose } from "@plasmicpkgs/radix-ui";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicDialogTooltip.module.css"; // plasmic-import: Ja5GPSQ1q6Qz/css

import ChevronRightIcon from "./icons/PlasmicIcon__ChevronRight"; // plasmic-import: asThzEchEMNJ/icon
import ChevronLeftIcon from "./icons/PlasmicIcon__ChevronLeft"; // plasmic-import: vQC4_6sr1Yuo/icon
import XIcon from "./icons/PlasmicIcon__X"; // plasmic-import: YuRnfxQGHRim/icon

createPlasmicElementProxy;

export type PlasmicDialogTooltip__VariantMembers = {
  fullpage: "fullpage";
};
export type PlasmicDialogTooltip__VariantsArgs = {
  fullpage?: SingleBooleanChoiceArg<"fullpage">;
};
type VariantPropType = keyof PlasmicDialogTooltip__VariantsArgs;
export const PlasmicDialogTooltip__VariantProps = new Array<VariantPropType>(
  "fullpage"
);

export type PlasmicDialogTooltip__ArgsType = {
  opendialog?: boolean;
  onOpendialogChange?: (val: string) => void;
  data?: any;
  token?: string;
};
type ArgPropType = keyof PlasmicDialogTooltip__ArgsType;
export const PlasmicDialogTooltip__ArgProps = new Array<ArgPropType>(
  "opendialog",
  "onOpendialogChange",
  "data",
  "token"
);

export type PlasmicDialogTooltip__OverridesType = {
  dialog3?: Flex__<typeof Dialog>;
  button3?: Flex__<typeof Button2>;
  dialogContent?: Flex__<typeof DialogContent>;
  dialogTitle?: Flex__<typeof DialogTitle>;
  load?: Flex__<typeof Load>;
  dialogClose?: Flex__<typeof DialogClose>;
};

export interface DefaultDialogTooltipProps {
  opendialog?: boolean;
  onOpendialogChange?: (val: string) => void;
  data?: any;
  token?: string;
  fullpage?: SingleBooleanChoiceArg<"fullpage">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDialogTooltip__RenderFunc(props: {
  variants: PlasmicDialogTooltip__VariantsArgs;
  args: PlasmicDialogTooltip__ArgsType;
  overrides: PlasmicDialogTooltip__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          data: {
            success: true,
            result: {
              dialogs: [
                {
                  acceptTextColor: "#ffffff",
                  rejectTextColor: "#52a382",
                  acceptText:
                    "\u0641\u0639\u0627\u0644 \u06a9\u0646\u06cc\u0645",
                  acceptAction: "#healthSubscription",
                  title:
                    "\u067e\u06cc\u0627\u0645\u06a9 \u0627\u0637\u0644\u0627\u0639 \u0631\u0633\u0627\u0646\u06cc \u0628\u0647 \u0647\u0645\u0633\u0631\u062a",
                  type: "native",
                  createdAt: "datetime()",
                  titleColor: "#2B6D50",
                  isSpecial: false,
                  text: "\u0645\u0627 \u0627\u06cc\u0646\u062c\u0627\u06cc\u06cc\u0645 \u062a\u0627 <b>\u0647\u0645\u0633\u0631\u062a \u0628\u062f\u0648\u0646\u0647 \u0686\u0647 \u062a\u063a\u06cc\u06cc\u0631\u0627\u062a\u06cc \u062f\u0631 \u0645\u0633\u06cc\u0631 \u0628\u0627\u0631\u062f\u0627\u0631\u06cc \u062a\u062c\u0631\u0628\u0647 \u0645\u06cc\u200c\u06a9\u0646\u06cc</b> \u0648 \u0686\u0637\u0648\u0631 \u0645\u06cc\u200c\u062a\u0648\u0646\u0647 \u0628\u0647\u062a\u0631\u06cc\u0646 \u0647\u0645\u0631\u0627\u0647 \u062a\u0648 \u0628\u0627\u0634\u0647.\u0627\u06cc\u0646\u0637\u0648\u0631\u06cc \u062f\u06cc\u06af\u0647 \u0686\u06cc\u0632\u06cc \u06cc\u0627\u062f\u0634 \u0646\u0645\u06cc\u0631\u0647 \u0686\u0648\u0646<b> \u0647\u0631 \u0647\u0641\u062a\u0647 \u0628\u0647\u0634 \u0645\u06cc\u06af\u06cc\u0645:</b><br>\u25cf \u0686\u0647 \u062a\u063a\u06cc\u06cc\u0631\u0627\u062a\u06cc \u062f\u0631 \u0628\u062f\u0646 \u062a\u0648 \u0648 \u0641\u0631\u0632\u0646\u062f\u062a\u0648\u0646 \u0631\u062e \u0645\u06cc\u200c\u062f\u0647<br>\u25cf \u0646\u06a9\u0627\u062a\u06cc \u0628\u0631\u0627\u06cc \u0627\u06cc\u0646\u06a9\u0647 \u0686\u0637\u0648\u0631 \u0628\u0647\u062a\u0631 \u0627\u0632 \u062a\u0648 \u062d\u0645\u0627\u06cc\u062a \u06a9\u0646\u0647<br>\u25cf \u0646\u06a9\u0627\u062a \u06a9\u0627\u0631\u0628\u0631\u062f\u06cc \u06a9\u0647 \u0647\u0631 \u067e\u062f\u0631\u06cc \u0628\u0627\u06cc\u062f \u0628\u062f\u0648\u0646\u0647<br><br>.<b>\u0645\u06cc\u200c\u062e\u0648\u0627\u06cc \u0647\u0645\u06cc\u0646 \u0647\u0641\u062a\u0647 \u0627\u06cc\u0646 \u0627\u0634\u062a\u0631\u0627\u06a9 \u0631\u0648 \u0628\u0631\u0627\u06cc \u0647\u0645\u0633\u0631\u062a \u0641\u0639\u0627\u0644 \u06a9\u0646\u06cc\u061f \ud83d\udc9b</b>",
                  id: "apoc.create.uuid()",
                  startAt: "datetime()",
                  updatedAt: "datetime()",
                  backgroundColor: "#E8F9F1",
                  active: false,
                  rejectText:
                    "\u0628\u0627\u0634\u0647 \u0628\u0639\u062f\u0627",
                  disableViewCondition: 0,
                  textColor: "#52a382",
                  target: "pregnanyWeek1",
                  badge: "",
                  healthStatus: "pregnancy",
                  background: "#E8F9F1",
                  btnColor: "#52B888",
                  custom: true,
                  finishAt: "datetime()"
                }
              ]
            }
          }
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "dialog3.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $state.opendialog;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "opendialog",
        type: "writable",
        variableType: "boolean",

        valueProp: "opendialog",
        onChangeProp: "onOpendialogChange"
      },
      {
        path: "button3.color",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "button3.load",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "button3.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "fullpage",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.fullpage
      },
      {
        path: "load.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  const $globalActions = useGlobalActions?.();

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <Dialog
      data-plasmic-name={"dialog3"}
      data-plasmic-override={overrides.dialog3}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        "root_reset_qARqpE4p5tZmJuNxFbTaPz",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.dialog3,
        { [sty.dialog3fullpage]: hasVariant($state, "fullpage", "fullpage") }
      )}
      defaultOpen={(() => {
        try {
          return $state.opendialog;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return undefined;
          }
          throw e;
        }
      })()}
      onOpenChange={async (...eventArgs: any) => {
        generateStateOnChangeProp($state, ["dialog3", "open"]).apply(
          null,
          eventArgs
        );

        (async open => {
          const $steps = {};

          $steps["updateOpendialog"] = true
            ? (() => {
                const actionArgs = {
                  variable: {
                    objRoot: $state,
                    variablePath: ["opendialog"]
                  },
                  operation: 4
                };
                return (({ variable, value, startIndex, deleteCount }) => {
                  if (!variable) {
                    return;
                  }
                  const { objRoot, variablePath } = variable;

                  const oldValue = $stateGet(objRoot, variablePath);
                  $stateSet(objRoot, variablePath, !oldValue);
                  return !oldValue;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateOpendialog"] != null &&
            typeof $steps["updateOpendialog"] === "object" &&
            typeof $steps["updateOpendialog"].then === "function"
          ) {
            $steps["updateOpendialog"] = await $steps["updateOpendialog"];
          }
        }).apply(null, eventArgs);
      }}
      open={generateStateValueProp($state, ["dialog3", "open"])}
      overlayClassName={classNames({
        [sty["pcls_A2fTnGZ8E1fS"]]: hasVariant($state, "fullpage", "fullpage"),
        [sty["pcls_X0T0CvvcULBI"]]: hasVariant(
          globalVariants,
          "screen",
          "mobileOnly"
        ),
        [sty["pcls_Z2_dmxW1IHjQ"]]: true
      })}
      themeResetClass={classNames(
        "root_reset_qARqpE4p5tZmJuNxFbTaPz",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames
      )}
      triggerSlot={
        <Button2
          data-plasmic-name={"button3"}
          data-plasmic-override={overrides.button3}
          className={classNames("__wab_instance", sty.button3)}
          color={generateStateValueProp($state, ["button3", "color"])}
          endIcon={
            <ChevronLeftIcon
              className={classNames("all", sty.svg__prbTy)}
              role={"img"}
            />
          }
          load={generateStateValueProp($state, ["button3", "load"])}
          loading={generateStateValueProp($state, ["button3", "loading"])}
          onColorChange={async (...eventArgs: any) => {
            ((...eventArgs) => {
              generateStateOnChangeProp($state, ["button3", "color"])(
                eventArgs[0]
              );
            }).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          onLoadChange={async (...eventArgs: any) => {
            ((...eventArgs) => {
              generateStateOnChangeProp($state, ["button3", "load"])(
                eventArgs[0]
              );
            }).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          onLoadingChange={async (...eventArgs: any) => {
            ((...eventArgs) => {
              generateStateOnChangeProp($state, ["button3", "loading"])(
                eventArgs[0]
              );
            }).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          startIcon={
            <ChevronRightIcon
              className={classNames("all", sty.svg__r7Bor)}
              role={"img"}
            />
          }
          submitsForm={false}
        />
      }
    >
      <DialogContent
        data-plasmic-name={"dialogContent"}
        data-plasmic-override={overrides.dialogContent}
        className={classNames("__wab_instance", sty.dialogContent, {
          [sty.dialogContentfullpage]: hasVariant(
            $state,
            "fullpage",
            "fullpage"
          )
        })}
        enterAnimations={
          hasVariant(globalVariants, "screen", "mobileOnly")
            ? ["slide-in-from-bottom"]
            : ["zoom-enter", "fade-in"]
        }
        enterDuration={0.5}
        exitAnimations={
          hasVariant(globalVariants, "screen", "mobileOnly")
            ? ["slide-out-to-bottom"]
            : ["zoom-exit", "fade-out"]
        }
        exitDuration={0.5}
        themeResetClass={classNames(
          "root_reset_qARqpE4p5tZmJuNxFbTaPz",
          "plasmic_default_styles",
          "plasmic_mixins",
          styleTokensClassNames
        )}
      >
        <DialogTitle
          data-plasmic-name={"dialogTitle"}
          data-plasmic-override={overrides.dialogTitle}
          className={classNames("__wab_instance", sty.dialogTitle)}
        >
          <div className={classNames("all", "__wab_text", sty.text__i4K6G)}>
            {"Sheet title"}
          </div>
        </DialogTitle>
        <div
          className={classNames("all", sty.freeBox__ozWyq)}
          style={(() => {
            try {
              return {
                background: $props.data.result.dialogs[0].backgroundColor
              };
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
        >
          <div
            className={classNames("all", "__wab_text", sty.text__gCqMx)}
            style={(() => {
              try {
                return { color: $props.data.result.dialogs[0].titleColor };
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.data.result.dialogs[0].title;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
          <div
            className={classNames("all", "__wab_text", sty.text__rmsFx)}
            style={(() => {
              try {
                return { color: $props.data.result.dialogs[0].textColor };
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
          >
            <div
              className={"__wab_expr_html_text"}
              dangerouslySetInnerHTML={{
                __html: (() => {
                  try {
                    return $props.data.result.dialogs[0].text;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "";
                    }
                    throw e;
                  }
                })()
              }}
            />
          </div>
          <Load
            data-plasmic-name={"load"}
            data-plasmic-override={overrides.load}
            className={classNames("__wab_instance", sty.load)}
            loading={generateStateValueProp($state, ["load", "loading"])}
            onLoadingChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["load", "loading"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
          />

          <div className={classNames("all", sty.freeBox__kCwyM)}>
            <div
              className={classNames("all", sty.freeBox__xsbDk)}
              onClick={async event => {
                const $steps = {};

                $steps["updateDialog3Open2"] = true
                  ? (() => {
                      const actionArgs = {
                        customFunction: async () => {
                          return ($state.load.loading = true);
                        }
                      };
                      return (({ customFunction }) => {
                        return customFunction();
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateDialog3Open2"] != null &&
                  typeof $steps["updateDialog3Open2"] === "object" &&
                  typeof $steps["updateDialog3Open2"].then === "function"
                ) {
                  $steps["updateDialog3Open2"] =
                    await $steps["updateDialog3Open2"];
                }

                $steps["invokeGlobalAction"] = false
                  ? (() => {
                      const actionArgs = {
                        args: [
                          "POST",
                          "https://n8n.staas.ir/webhook/tools/selfCare/linkV3",
                          undefined,
                          (() => {
                            try {
                              return {
                                authorization: $props.token,
                                type: $props.data.result.dialogs[0].acceptAction
                              };
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                        ]
                      };
                      return $globalActions["Fragment.apiRequest"]?.apply(
                        null,
                        [...actionArgs.args]
                      );
                    })()
                  : undefined;
                if (
                  $steps["invokeGlobalAction"] != null &&
                  typeof $steps["invokeGlobalAction"] === "object" &&
                  typeof $steps["invokeGlobalAction"].then === "function"
                ) {
                  $steps["invokeGlobalAction"] =
                    await $steps["invokeGlobalAction"];
                }

                $steps["invokeGlobalAction2"] = true
                  ? (() => {
                      const actionArgs = {
                        args: [
                          (() => {
                            try {
                              return (
                                $props.data.result.dialogs[0].acceptActionV3 ||
                                $props.data.result.dialogs[0].acceptAction ||
                                $props.data.result.dialogs[0].acceptActionV2
                              );
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })(),
                          (() => {
                            try {
                              return $props.token;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                        ]
                      };
                      return $globalActions["Fragment.deepLink"]?.apply(null, [
                        ...actionArgs.args
                      ]);
                    })()
                  : undefined;
                if (
                  $steps["invokeGlobalAction2"] != null &&
                  typeof $steps["invokeGlobalAction2"] === "object" &&
                  typeof $steps["invokeGlobalAction2"].then === "function"
                ) {
                  $steps["invokeGlobalAction2"] =
                    await $steps["invokeGlobalAction2"];
                }

                $steps["runCode"] = true
                  ? (() => {
                      const actionArgs = {
                        customFunction: async () => {
                          return ($state.load.loading = false);
                        }
                      };
                      return (({ customFunction }) => {
                        return customFunction();
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["runCode"] != null &&
                  typeof $steps["runCode"] === "object" &&
                  typeof $steps["runCode"].then === "function"
                ) {
                  $steps["runCode"] = await $steps["runCode"];
                }
              }}
              style={(() => {
                try {
                  return { background: $props.data.result.dialogs[0].btnColor };
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
            >
              <div
                className={classNames("all", "__wab_text", sty.text__g7UE1)}
                style={(() => {
                  try {
                    return {
                      color: $props.data.result.dialogs[0].acceptTextColor
                    };
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return (
                        $props.data.result.dialogs[0].btnText ||
                        $props.data.result.dialogs[0].acceptText
                      );
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
            </div>
            <div
              className={classNames("all", sty.freeBox__rq6Q)}
              onClick={async event => {
                const $steps = {};

                $steps["updateDialog3Open"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["dialog3", "open"]
                        },
                        operation: 0,
                        value: false
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateDialog3Open"] != null &&
                  typeof $steps["updateDialog3Open"] === "object" &&
                  typeof $steps["updateDialog3Open"].then === "function"
                ) {
                  $steps["updateDialog3Open"] =
                    await $steps["updateDialog3Open"];
                }
              }}
              style={(() => {
                try {
                  return {
                    background: $props.data.result.dialogs[0].backgroundColor
                  };
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
            >
              <div
                className={classNames("all", "__wab_text", sty.text__jb7V1)}
                style={(() => {
                  try {
                    return {
                      color: $props.data.result.dialogs[0].rejectTextColor
                    };
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return $props.data.result.dialogs[0].rejectText;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
            </div>
          </div>
        </div>
        <DialogClose
          data-plasmic-name={"dialogClose"}
          data-plasmic-override={overrides.dialogClose}
          className={classNames("__wab_instance", sty.dialogClose)}
        >
          <XIcon className={classNames("all", sty.svg__mDlTz)} role={"img"} />
        </DialogClose>
      </DialogContent>
    </Dialog>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  dialog3: [
    "dialog3",
    "button3",
    "dialogContent",
    "dialogTitle",
    "load",
    "dialogClose"
  ],
  button3: ["button3"],
  dialogContent: ["dialogContent", "dialogTitle", "load", "dialogClose"],
  dialogTitle: ["dialogTitle"],
  load: ["load"],
  dialogClose: ["dialogClose"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  dialog3: typeof Dialog;
  button3: typeof Button2;
  dialogContent: typeof DialogContent;
  dialogTitle: typeof DialogTitle;
  load: typeof Load;
  dialogClose: typeof DialogClose;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDialogTooltip__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDialogTooltip__VariantsArgs;
    args?: PlasmicDialogTooltip__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicDialogTooltip__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicDialogTooltip__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDialogTooltip__ArgProps,
          internalVariantPropNames: PlasmicDialogTooltip__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDialogTooltip__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "dialog3") {
    func.displayName = "PlasmicDialogTooltip";
  } else {
    func.displayName = `PlasmicDialogTooltip.${nodeName}`;
  }
  return func;
}

export const PlasmicDialogTooltip = Object.assign(
  // Top-level PlasmicDialogTooltip renders the root element
  makeNodeComponent("dialog3"),
  {
    // Helper components rendering sub-elements
    button3: makeNodeComponent("button3"),
    dialogContent: makeNodeComponent("dialogContent"),
    dialogTitle: makeNodeComponent("dialogTitle"),
    load: makeNodeComponent("load"),
    dialogClose: makeNodeComponent("dialogClose"),

    // Metadata about props expected for PlasmicDialogTooltip
    internalVariantProps: PlasmicDialogTooltip__VariantProps,
    internalArgProps: PlasmicDialogTooltip__ArgProps
  }
);

export default PlasmicDialogTooltip;
/* prettier-ignore-end */
