/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qARqpE4p5tZmJuNxFbTaPz
// Component: 8LUOC3uVttVT

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Dialog from "../../Dialog"; // plasmic-import: AoPc4Hy8St02/component
import { DatePickers } from "@/components/DatePickers"; // plasmic-import: Dz5TQ2vEY9XS/codeComponent
import Button from "../../Button"; // plasmic-import: 2MRRFY7jUAge/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicDateInput.module.css"; // plasmic-import: 8LUOC3uVttVT/css

import Icon290Icon from "./icons/PlasmicIcon__Icon290"; // plasmic-import: R1YQDitcVUYD/icon
import Icon11Icon from "./icons/PlasmicIcon__Icon11"; // plasmic-import: TLjQehPXSyaR/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 4RgfxZWAffAT/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: cDVOBX0F9d9g/icon

createPlasmicElementProxy;

export type PlasmicDateInput__VariantMembers = {};
export type PlasmicDateInput__VariantsArgs = {};
type VariantPropType = keyof PlasmicDateInput__VariantsArgs;
export const PlasmicDateInput__VariantProps = new Array<VariantPropType>();

export type PlasmicDateInput__ArgsType = {
  date?: any;
  onDateChange?: (val: string) => void;
};
type ArgPropType = keyof PlasmicDateInput__ArgsType;
export const PlasmicDateInput__ArgProps = new Array<ArgPropType>(
  "date",
  "onDateChange"
);

export type PlasmicDateInput__OverridesType = {
  root?: Flex__<"div">;
  dialog?: Flex__<typeof Dialog>;
  datePickers?: Flex__<typeof DatePickers>;
  button3?: Flex__<typeof Button>;
};

export interface DefaultDateInputProps {
  date?: any;
  onDateChange?: (val: string) => void;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDateInput__RenderFunc(props: {
  variants: PlasmicDateInput__VariantsArgs;
  args: PlasmicDateInput__ArgsType;
  overrides: PlasmicDateInput__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "dialog.opendialog",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "datePickers.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ({})
      },
      {
        path: "button3.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "date",
        type: "writable",
        variableType: "object",

        valueProp: "date",
        onChangeProp: "onDateChange"
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_qARqpE4p5tZmJuNxFbTaPz",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames("all", sty.freeBox__u85Yt)}>
        <div
          className={classNames("all", sty.freeBox__iXkVf)}
          onClick={async event => {
            const $steps = {};

            $steps["updateDialogOpendialog"] = true
              ? (() => {
                  const actionArgs = {
                    variable: {
                      objRoot: $state,
                      variablePath: ["dialog", "opendialog"]
                    },
                    operation: 0,
                    value: true
                  };
                  return (({ variable, value, startIndex, deleteCount }) => {
                    if (!variable) {
                      return;
                    }
                    const { objRoot, variablePath } = variable;

                    $stateSet(objRoot, variablePath, value);
                    return value;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateDialogOpendialog"] != null &&
              typeof $steps["updateDialogOpendialog"] === "object" &&
              typeof $steps["updateDialogOpendialog"].then === "function"
            ) {
              $steps["updateDialogOpendialog"] =
                await $steps["updateDialogOpendialog"];
            }
          }}
        >
          <Icon290Icon
            className={classNames("all", sty.svg__l8Toh)}
            role={"img"}
          />

          {(() => {
            try {
              return !$state.date.day;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div className={classNames("all", "__wab_text", sty.text__coqJh)}>
              <React.Fragment>
                {(() => {
                  try {
                    return "مثال:  1405/06/07";
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "\u0645\u062b\u0627\u0644 1406/5/1";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          ) : null}
          {(() => {
            try {
              return $state.date.day;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div className={classNames("all", "__wab_text", sty.text__cpyAr)}>
              <React.Fragment>
                {(() => {
                  try {
                    return `${$state.date.day} / ${$state.date.month} / ${$state.date.year}`;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "\u0645\u062b\u0627\u0644 1406/5/1";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          ) : null}
        </div>
        {(() => {
          try {
            return $state.date.day;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return true;
            }
            throw e;
          }
        })() ? (
          <Icon11Icon
            className={classNames("all", sty.svg__hcz4Y)}
            onClick={async event => {
              const $steps = {};

              $steps["runCode"] = true
                ? (() => {
                    const actionArgs = {
                      customFunction: async () => {
                        return ($state.date = {});
                      }
                    };
                    return (({ customFunction }) => {
                      return customFunction();
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runCode"] != null &&
                typeof $steps["runCode"] === "object" &&
                typeof $steps["runCode"].then === "function"
              ) {
                $steps["runCode"] = await $steps["runCode"];
              }
            }}
            role={"img"}
          />
        ) : null}
      </div>
      <Dialog
        data-plasmic-name={"dialog"}
        data-plasmic-override={overrides.dialog}
        className={classNames("__wab_instance", sty.dialog)}
        colorback={"w"}
        onOpendialogChange={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["dialog", "opendialog"]).apply(
            null,
            eventArgs
          );

          if (
            eventArgs.length > 1 &&
            eventArgs[1] &&
            eventArgs[1]._plasmic_state_init_
          ) {
            return;
          }
        }}
        opendialog={generateStateValueProp($state, ["dialog", "opendialog"])}
      >
        <div className={classNames("all", sty.freeBox__grNsq)}>
          <DatePickers
            data-plasmic-name={"datePickers"}
            data-plasmic-override={overrides.datePickers}
            SelectedDay={10}
            SelectedMonth={10}
            SelectedYear={1379}
            className={classNames("__wab_instance", sty.datePickers)}
            customYears={(() => {
              try {
                return (() => {
                  const currentYearNum = parseInt(
                    new Intl.DateTimeFormat("fa-IR-u-nu-latn", {
                      year: "numeric"
                    }).format(new Date())
                  );
                  const yearsStringArray = [currentYearNum, currentYearNum + 1];

                  return yearsStringArray;
                })();
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return [];
                }
                throw e;
              }
            })()}
            hideYear={false}
            onChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["datePickers", "value"]).apply(
                null,
                eventArgs
              );
            }}
            selectedValues={generateStateValueProp($state, [
              "datePickers",
              "value"
            ])}
          />

          <Button
            data-plasmic-name={"button3"}
            data-plasmic-override={overrides.button3}
            className={classNames("__wab_instance", sty.button3)}
            color={"success"}
            label={
              <div className={classNames("all", "__wab_text", sty.text__vx4A8)}>
                {"\u062a\u0627\u06cc\u06cc\u062f"}
              </div>
            }
            loading={generateStateValueProp($state, ["button3", "loading"])}
            onClick={async event => {
              const $steps = {};

              $steps["runCode"] = true
                ? (() => {
                    const actionArgs = {
                      customFunction: async () => {
                        return (() => {
                          $state.date = $state.datePickers.value;
                          return ($state.dialog.opendialog = false);
                        })();
                      }
                    };
                    return (({ customFunction }) => {
                      return customFunction();
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runCode"] != null &&
                typeof $steps["runCode"] === "object" &&
                typeof $steps["runCode"].then === "function"
              ) {
                $steps["runCode"] = await $steps["runCode"];
              }
            }}
            onLoadingChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["button3", "loading"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
          />
        </div>
      </Dialog>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "dialog", "datePickers", "button3"],
  dialog: ["dialog", "datePickers", "button3"],
  datePickers: ["datePickers"],
  button3: ["button3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  dialog: typeof Dialog;
  datePickers: typeof DatePickers;
  button3: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDateInput__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDateInput__VariantsArgs;
    args?: PlasmicDateInput__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicDateInput__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicDateInput__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDateInput__ArgProps,
          internalVariantPropNames: PlasmicDateInput__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDateInput__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDateInput";
  } else {
    func.displayName = `PlasmicDateInput.${nodeName}`;
  }
  return func;
}

export const PlasmicDateInput = Object.assign(
  // Top-level PlasmicDateInput renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dialog: makeNodeComponent("dialog"),
    datePickers: makeNodeComponent("datePickers"),
    button3: makeNodeComponent("button3"),

    // Metadata about props expected for PlasmicDateInput
    internalVariantProps: PlasmicDateInput__VariantProps,
    internalArgProps: PlasmicDateInput__ArgProps
  }
);

export default PlasmicDateInput;
/* prettier-ignore-end */
