/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qARqpE4p5tZmJuNxFbTaPz
// Component: FYuKeNpu5zZ7

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import TopPage from "../../TopPage"; // plasmic-import: g_3hTxUM0f5d/component
import MainPage from "../../MainPage"; // plasmic-import: xrEadpE-s6jI/component
import CenterPage from "../../CenterPage"; // plasmic-import: fRNzpZPnnILn/component
import Modal from "../../Modal"; // plasmic-import: Oo9r7A7X8FP7/component
import Button from "../../Button"; // plasmic-import: 2MRRFY7jUAge/component
import { AntdTabs } from "@plasmicpkgs/antd5/skinny/registerTabs";
import { AntdTabItem } from "@plasmicpkgs/antd5/skinny/registerTabs";
import CenterInfo from "../../CenterInfo"; // plasmic-import: 5fhUfrSk0s6y/component
import Imag from "../../Imag"; // plasmic-import: ScLhJpeVxPbk/component
import Loaction from "../../Loaction"; // plasmic-import: sTw08-1jIWRS/component
import AddServise from "../../AddServise"; // plasmic-import: GoiLccUqO4vp/component
import TimeWeek from "../../TimeWeek"; // plasmic-import: cN1_ZVwWpEB8/component
import { ApiRequest } from "@/fragment/components/api-request"; // plasmic-import: TUk6VD6AhbGJ/codeComponent
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { _useGlobalVariants } from "../website_starter/plasmic"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectModule
import { _useStyleTokens } from "../website_starter/PlasmicStyleTokensProvider"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../website_starter/plasmic.module.css"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectcss
import sty from "./PlasmicMain.module.css"; // plasmic-import: FYuKeNpu5zZ7/css

import CircleIcon from "../website_starter/icons/PlasmicIcon__Circle"; // plasmic-import: 4RgfxZWAffAT/icon
import ChevronDownIcon from "../website_starter/icons/PlasmicIcon__ChevronDown"; // plasmic-import: cDVOBX0F9d9g/icon

createPlasmicElementProxy;

export type PlasmicMain__VariantMembers = {
  page: "centerList" | "center";
};
export type PlasmicMain__VariantsArgs = {
  page?: SingleChoiceArg<"centerList" | "center">;
};
type VariantPropType = keyof PlasmicMain__VariantsArgs;
export const PlasmicMain__VariantProps = new Array<VariantPropType>("page");

export type PlasmicMain__ArgsType = {
  centerId?: string;
  role?: string;
  onRoleChange?: (val: string) => void;
};
type ArgPropType = keyof PlasmicMain__ArgsType;
export const PlasmicMain__ArgProps = new Array<ArgPropType>(
  "centerId",
  "role",
  "onRoleChange"
);

export type PlasmicMain__OverridesType = {
  root?: Flex__<"div">;
  topPage?: Flex__<typeof TopPage>;
  mainPage?: Flex__<typeof MainPage>;
  centerPage?: Flex__<typeof CenterPage>;
  addCenter?: Flex__<typeof Modal>;
  tabs?: Flex__<typeof AntdTabs>;
  centerInfo?: Flex__<typeof CenterInfo>;
  imag?: Flex__<typeof Imag>;
  loaction?: Flex__<typeof Loaction>;
  addServise?: Flex__<typeof AddServise>;
  timeWeek?: Flex__<typeof TimeWeek>;
  freeBox?: Flex__<"div">;
  button2?: Flex__<typeof Button>;
  submit?: Flex__<typeof Button>;
  button3?: Flex__<typeof Button>;
  categories?: Flex__<typeof ApiRequest>;
  embedHtml?: Flex__<typeof Embed>;
};

export interface DefaultMainProps {
  centerId?: string;
  role?: string;
  onRoleChange?: (val: string) => void;
  page?: SingleChoiceArg<"centerList" | "center">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMain__RenderFunc(props: {
  variants: PlasmicMain__VariantsArgs;
  args: PlasmicMain__ArgsType;
  overrides: PlasmicMain__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          centerId: "a87ff679a2f3e71d9181a67b7542122c"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "tabs.activeKey",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => "1"
      },
      {
        path: "addCenter.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          hasVariant($state, "page", "centerList") ? false : false
      },
      {
        path: "button2.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "button3.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "submit.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "addServise.servises",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => []
      },
      {
        path: "categories.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "categories.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "categories.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "loaction.city2",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "loaction.state2",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "loaction.call2",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "loaction.address",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "loaction.lon",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "loaction.lat",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "mainPage.categpty",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $state.categories.data.result;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()
      },
      {
        path: "timeWeek.week",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => [
          { label: "\u0634\u0646\u0628\u0647", value: "sat", isHoliday: false },
          {
            label: "\u06cc\u06a9\u0634\u0646\u0628\u0647",
            value: "sun",
            isHoliday: false
          },
          {
            label: "\u062f\u0648\u0634\u0646\u0628\u0647",
            value: "mon",
            isHoliday: false
          },
          {
            label: "\u0633\u0647\u200c\u0634\u0646\u0628\u0647",
            value: "tue",
            isHoliday: false
          },
          {
            label: "\u0686\u0647\u0627\u0631\u0634\u0646\u0628\u0647",
            value: "wed",
            isHoliday: false
          },
          {
            label: "\u067e\u0646\u062c\u200c\u0634\u0646\u0628\u0647",
            value: "thu",
            isHoliday: false
          },
          { label: "\u062c\u0645\u0639\u0647", value: "fri", isHoliday: false }
        ]
      },
      {
        path: "imag.uploadFiles",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => []
      },
      {
        path: "mainPage.selectedRow",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "button.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "page",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.page
      },
      {
        path: "centerPage.categpty",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => []
      },
      {
        path: "role",
        type: "writable",
        variableType: "text",

        valueProp: "role",
        onChangeProp: "onRoleChange"
      },
      {
        path: "centerInfo.title",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "centerInfo.subcategory2",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => "1"
      },
      {
        path: "centerInfo.categorie",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => "1"
      },
      {
        path: "centerInfo.description",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "centerInfo.tag",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "centerInfo.categories",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $state.categories?.data?.result;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <TopPage
        data-plasmic-name={"topPage"}
        data-plasmic-override={overrides.topPage}
        className={classNames("__wab_instance", sty.topPage, {
          [sty.topPagepage_center]: hasVariant($state, "page", "center")
        })}
      />

      <MainPage
        data-plasmic-name={"mainPage"}
        data-plasmic-override={overrides.mainPage}
        categpty={generateStateValueProp($state, ["mainPage", "categpty"])}
        className={classNames("__wab_instance", sty.mainPage, {
          [sty.mainPagepage_centerList]: hasVariant(
            $state,
            "page",
            "centerList"
          ),
          [sty.mainPagepage_center]: hasVariant($state, "page", "center")
        })}
        onCategptyChange={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["mainPage", "categpty"]).apply(
            null,
            eventArgs
          );

          if (
            eventArgs.length > 1 &&
            eventArgs[1] &&
            eventArgs[1]._plasmic_state_init_
          ) {
            return;
          }
        }}
        onRowClicked={async (rowKey, row, event) => {
          const $steps = {};

          $steps["goToPanel"] = true
            ? (() => {
                const actionArgs = {
                  destination: `/panel/${(() => {
                    try {
                      return "center-" + $state.mainPage.selectedRow.id;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}`
                };
                return (({ destination }) => {
                  if (
                    typeof destination === "string" &&
                    destination.startsWith("#")
                  ) {
                    document
                      .getElementById(destination.substr(1))
                      .scrollIntoView({ behavior: "smooth" });
                  } else {
                    __nextRouter?.push(destination);
                  }
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["goToPanel"] != null &&
            typeof $steps["goToPanel"] === "object" &&
            typeof $steps["goToPanel"].then === "function"
          ) {
            $steps["goToPanel"] = await $steps["goToPanel"];
          }
        }}
        onSelectedRowChange={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["mainPage", "selectedRow"]).apply(
            null,
            eventArgs
          );

          if (
            eventArgs.length > 1 &&
            eventArgs[1] &&
            eventArgs[1]._plasmic_state_init_
          ) {
            return;
          }
        }}
        openEdit={async event => {
          const $steps = {};

          $steps["updateAddCenterIsOpen"] = true
            ? (() => {
                const actionArgs = {
                  variable: {
                    objRoot: $state,
                    variablePath: ["addCenter", "isOpen"]
                  },
                  operation: 4
                };
                return (({ variable, value, startIndex, deleteCount }) => {
                  if (!variable) {
                    return;
                  }
                  const { objRoot, variablePath } = variable;

                  const oldValue = $stateGet(objRoot, variablePath);
                  $stateSet(objRoot, variablePath, !oldValue);
                  return !oldValue;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateAddCenterIsOpen"] != null &&
            typeof $steps["updateAddCenterIsOpen"] === "object" &&
            typeof $steps["updateAddCenterIsOpen"].then === "function"
          ) {
            $steps["updateAddCenterIsOpen"] =
              await $steps["updateAddCenterIsOpen"];
          }
        }}
        selectedRow={generateStateValueProp($state, [
          "mainPage",
          "selectedRow"
        ])}
      />

      <CenterPage
        data-plasmic-name={"centerPage"}
        data-plasmic-override={overrides.centerPage}
        categpty={generateStateValueProp($state, ["centerPage", "categpty"])}
        className={classNames("__wab_instance", sty.centerPage, {
          [sty.centerPagepage_centerList]: hasVariant(
            $state,
            "page",
            "centerList"
          ),
          [sty.centerPagepage_center]: hasVariant($state, "page", "center")
        })}
        id={args.centerId}
        onCategptyChange={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["centerPage", "categpty"]).apply(
            null,
            eventArgs
          );

          if (
            eventArgs.length > 1 &&
            eventArgs[1] &&
            eventArgs[1]._plasmic_state_init_
          ) {
            return;
          }
        }}
        role={(() => {
          try {
            return (() => {
              {
                {
                  return (() => {
                    const parts = $state.role.split("_");
                    return (
                      parts[0] +
                      parts[1].charAt(0).toUpperCase() +
                      parts[1].slice(1)
                    );
                  })();
                }
              }
            })();
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return [];
            }
            throw e;
          }
        })()}
        tagsitem={(() => {
          try {
            return $state.categories.data.tag;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
      />

      <Modal
        data-plasmic-name={"addCenter"}
        data-plasmic-override={overrides.addCenter}
        className={classNames("__wab_instance", sty.addCenter, {
          [sty.addCenterpage_centerList]: hasVariant(
            $state,
            "page",
            "centerList"
          ),
          [sty.addCenterpage_center]: hasVariant($state, "page", "center")
        })}
        closeOnBackdropClick={false}
        content={
          <AntdTabs
            data-plasmic-name={"tabs"}
            data-plasmic-override={overrides.tabs}
            activeKey={generateStateValueProp($state, ["tabs", "activeKey"])}
            animateTabBar={true}
            animateTabContent={false}
            animated={true}
            className={classNames("__wab_instance", sty.tabs)}
            defaultActiveKey={"1"}
            items={
              <React.Fragment>
                <AntdTabItem
                  className={classNames("__wab_instance", sty.tabItem__m6Scq)}
                  key={"1"}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vuwH
                      )}
                    >
                      {"\u0627\u0637\u0644\u0627\u0639\u0627\u062a"}
                    </div>
                  }
                >
                  <CenterInfo
                    data-plasmic-name={"centerInfo"}
                    data-plasmic-override={overrides.centerInfo}
                    categorie={generateStateValueProp($state, [
                      "centerInfo",
                      "categorie"
                    ])}
                    categories={generateStateValueProp($state, [
                      "centerInfo",
                      "categories"
                    ])}
                    className={classNames("__wab_instance", sty.centerInfo)}
                    description={generateStateValueProp($state, [
                      "centerInfo",
                      "description"
                    ])}
                    onCategorieChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "centerInfo",
                        "categorie"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    onCategoriesChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "centerInfo",
                        "categories"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    onDescriptionChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "centerInfo",
                        "description"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    onSubcategory2Change={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "centerInfo",
                        "subcategory2"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    onTagChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "centerInfo",
                        "tag"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    onTitleChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "centerInfo",
                        "title"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    subcategory2={generateStateValueProp($state, [
                      "centerInfo",
                      "subcategory2"
                    ])}
                    tag={generateStateValueProp($state, ["centerInfo", "tag"])}
                    tagsitem={$state.categories?.data?.tag}
                    title={generateStateValueProp($state, [
                      "centerInfo",
                      "title"
                    ])}
                  />
                </AntdTabItem>
                <AntdTabItem
                  className={classNames("__wab_instance", sty.tabItem___9Pwwy)}
                  key={"2"}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__q0V5E
                      )}
                    >
                      {"\u062a\u0635\u0627\u0648\u06cc\u0631"}
                    </div>
                  }
                >
                  <Imag
                    data-plasmic-name={"imag"}
                    data-plasmic-override={overrides.imag}
                    className={classNames("__wab_instance", sty.imag)}
                    onUploadFilesChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "imag",
                        "uploadFiles"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    uploadFiles={generateStateValueProp($state, [
                      "imag",
                      "uploadFiles"
                    ])}
                  />
                </AntdTabItem>
                <AntdTabItem
                  className={classNames("__wab_instance", sty.tabItem___7Ihuq)}
                  key={"3"}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xW6M
                      )}
                    >
                      {
                        "\u0622\u062f\u0631\u0633 \u0648 \u062a\u0645\u0627\u0633"
                      }
                    </div>
                  }
                >
                  <Loaction
                    data-plasmic-name={"loaction"}
                    data-plasmic-override={overrides.loaction}
                    address={generateStateValueProp($state, [
                      "loaction",
                      "address"
                    ])}
                    call2={generateStateValueProp($state, [
                      "loaction",
                      "call2"
                    ])}
                    city2={generateStateValueProp($state, [
                      "loaction",
                      "city2"
                    ])}
                    className={classNames("__wab_instance", sty.loaction)}
                    onAddressChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "loaction",
                        "address"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    onCallChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "loaction",
                        "call2"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    onCityChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "loaction",
                        "city2"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    onLatChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "loaction",
                        "lat"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    onLonChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "loaction",
                        "lon"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    onStateChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "loaction",
                        "state2"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    state2={generateStateValueProp($state, [
                      "loaction",
                      "state2"
                    ])}
                  />
                </AntdTabItem>
                <AntdTabItem
                  className={classNames("__wab_instance", sty.tabItem__hvk4I)}
                  key={"4"}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xwmKh
                      )}
                    >
                      {"\u0633\u0631\u0648\u06cc\u0633\u200c\u0647\u0627"}
                    </div>
                  }
                >
                  <AddServise
                    data-plasmic-name={"addServise"}
                    data-plasmic-override={overrides.addServise}
                    className={classNames("__wab_instance", sty.addServise)}
                    onServisesChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "addServise",
                        "servises"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    servises={generateStateValueProp($state, [
                      "addServise",
                      "servises"
                    ])}
                  />
                </AntdTabItem>
                <AntdTabItem
                  className={classNames("__wab_instance", sty.tabItem__aD35U)}
                  key={"5"}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ge21W
                      )}
                    >
                      {
                        "\u0633\u0627\u0639\u0627\u062a \u06a9\u0627\u0631\u06cc"
                      }
                    </div>
                  }
                >
                  <TimeWeek
                    data-plasmic-name={"timeWeek"}
                    data-plasmic-override={overrides.timeWeek}
                    className={classNames("__wab_instance", sty.timeWeek)}
                    onWeekChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "timeWeek",
                        "week"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    week={generateStateValueProp($state, ["timeWeek", "week"])}
                  />
                </AntdTabItem>
              </React.Fragment>
            }
            onChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["tabs", "activeKey"]).apply(
                null,
                eventArgs
              );
            }}
            size={"large"}
            sticky={false}
            tabBarBackground={"#FFF"}
            tabBarClassName={classNames({ [sty["pcls_gJZrIHSxavWd"]]: true })}
            tabPosition={"top"}
            tabsDropdownScopeClassName={sty["tabs__tabsDropdown"]}
            tabsScopeClassName={sty["tabs__tabs"]}
            type={"line"}
          />
        }
        footer={
          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            {(() => {
              try {
                return $state.tabs.activeKey != "5";
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <Button
                data-plasmic-name={"button2"}
                data-plasmic-override={overrides.button2}
                className={classNames("__wab_instance", sty.button2, {
                  [sty.button2page_centerList]: hasVariant(
                    $state,
                    "page",
                    "centerList"
                  )
                })}
                color={"success"}
                label={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hr43P
                    )}
                  >
                    {"\u0628\u0639\u062f\u06cc"}
                  </div>
                }
                loading={generateStateValueProp($state, ["button2", "loading"])}
                onClick={async event => {
                  const $steps = {};

                  $steps["runCode"] = true
                    ? (() => {
                        const actionArgs = {
                          customFunction: async () => {
                            return ($state.tabs.activeKey = (
                              parseInt($state.tabs.activeKey) + 1
                            ).toString());
                          }
                        };
                        return (({ customFunction }) => {
                          return customFunction();
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["runCode"] != null &&
                    typeof $steps["runCode"] === "object" &&
                    typeof $steps["runCode"].then === "function"
                  ) {
                    $steps["runCode"] = await $steps["runCode"];
                  }
                }}
                onLoadingChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "button2",
                    "loading"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
              />
            ) : null}
            {(() => {
              try {
                return $state.tabs.activeKey == "5";
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <Button
                data-plasmic-name={"submit"}
                data-plasmic-override={overrides.submit}
                className={classNames("__wab_instance", sty.submit)}
                color={"success"}
                label={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bSwNw
                    )}
                  >
                    {"\u0630\u062e\u06cc\u0631\u0647"}
                  </div>
                }
                loading={generateStateValueProp($state, ["submit", "loading"])}
                onClick={async event => {
                  const $steps = {};

                  $steps["updateSubmitLoading"] = true
                    ? (() => {
                        const actionArgs = {
                          variable: {
                            objRoot: $state,
                            variablePath: ["submit", "loading"]
                          },
                          operation: 0,
                          value: true
                        };
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;

                          $stateSet(objRoot, variablePath, value);
                          return value;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateSubmitLoading"] != null &&
                    typeof $steps["updateSubmitLoading"] === "object" &&
                    typeof $steps["updateSubmitLoading"].then === "function"
                  ) {
                    $steps["updateSubmitLoading"] =
                      await $steps["updateSubmitLoading"];
                  }

                  $steps["invokeGlobalAction"] = true
                    ? (() => {
                        const actionArgs = {
                          args: [
                            "POST",
                            "https://sayban.darkube.app/webhook/panel/center/add",
                            undefined,
                            (() => {
                              try {
                                return {
                                  name: $state.centerInfo.title,
                                  description: $state.centerInfo.description,
                                  subcategory_id:
                                    $state.centerInfo.subcategory2,
                                  address: $state.loaction.address,
                                  city: $state.loaction.city2,
                                  state: $state.loaction.state2,
                                  latitude: $state.loaction.lat,
                                  longitude: $state.loaction.lon,
                                  phone: $state.loaction.call2,
                                  image: $state.imag.uploadFiles,
                                  week: $state.timeWeek.week,
                                  tag: $state.centerInfo.tag,
                                  service: $state.addServise.servises
                                };
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()
                          ]
                        };
                        return $globalActions["Fragment.apiRequest"]?.apply(
                          null,
                          [...actionArgs.args]
                        );
                      })()
                    : undefined;
                  if (
                    $steps["invokeGlobalAction"] != null &&
                    typeof $steps["invokeGlobalAction"] === "object" &&
                    typeof $steps["invokeGlobalAction"].then === "function"
                  ) {
                    $steps["invokeGlobalAction"] =
                      await $steps["invokeGlobalAction"];
                  }

                  $steps["updateSubmitLoading2"] = true
                    ? (() => {
                        const actionArgs = {
                          variable: {
                            objRoot: $state,
                            variablePath: ["submit", "loading"]
                          },
                          operation: 0,
                          value: false
                        };
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;

                          $stateSet(objRoot, variablePath, value);
                          return value;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateSubmitLoading2"] != null &&
                    typeof $steps["updateSubmitLoading2"] === "object" &&
                    typeof $steps["updateSubmitLoading2"].then === "function"
                  ) {
                    $steps["updateSubmitLoading2"] =
                      await $steps["updateSubmitLoading2"];
                  }
                }}
                onLoadingChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "submit",
                    "loading"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
              />
            ) : null}
            <Button
              data-plasmic-name={"button3"}
              data-plasmic-override={overrides.button3}
              className={classNames("__wab_instance", sty.button3)}
              color={"neutral"}
              label={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__a4BhN
                  )}
                >
                  {"\u0644\u063a\u0648"}
                </div>
              }
              loading={generateStateValueProp($state, ["button3", "loading"])}
              onClick={async event => {
                const $steps = {};

                $steps["updateAddCenterIsOpen"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["addCenter", "isOpen"]
                        },
                        operation: 4
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        const oldValue = $stateGet(objRoot, variablePath);
                        $stateSet(objRoot, variablePath, !oldValue);
                        return !oldValue;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateAddCenterIsOpen"] != null &&
                  typeof $steps["updateAddCenterIsOpen"] === "object" &&
                  typeof $steps["updateAddCenterIsOpen"].then === "function"
                ) {
                  $steps["updateAddCenterIsOpen"] =
                    await $steps["updateAddCenterIsOpen"];
                }
              }}
              onLoadingChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, ["button3", "loading"]).apply(
                  null,
                  eventArgs
                );

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              type={"soft"}
            />
          </div>
        }
        heading={null}
        isOpen={generateStateValueProp($state, ["addCenter", "isOpen"])}
        onOpenChange={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["addCenter", "isOpen"]).apply(
            null,
            eventArgs
          );

          if (
            eventArgs.length > 1 &&
            eventArgs[1] &&
            eventArgs[1]._plasmic_state_init_
          ) {
            return;
          }
        }}
        showFooter={false}
        showHeader={false}
      />

      <ApiRequest
        data-plasmic-name={"categories"}
        data-plasmic-override={overrides.categories}
        children={null}
        className={classNames("__wab_instance", sty.categories, {
          [sty.categoriespage_center]: hasVariant($state, "page", "center")
        })}
        errorDisplay={null}
        loadingDisplay={null}
        method={"GET"}
        onError={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["categories", "error"]).apply(
            null,
            eventArgs
          );
        }}
        onLoading={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["categories", "loading"]).apply(
            null,
            eventArgs
          );
        }}
        onSuccess={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["categories", "data"]).apply(
            null,
            eventArgs
          );
        }}
        shouldFetch={true}
        url={"https://sayban.darkube.app/webhook/panel/categories/full"}
      />

      <Embed
        data-plasmic-name={"embedHtml"}
        data-plasmic-override={overrides.embedHtml}
        className={classNames("__wab_instance", sty.embedHtml)}
        code={
          '<script src="https://cdn.jsdelivr.net/npm/sortablejs@1.15.0/Sortable.min.js"></script>\r\n'
        }
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "topPage",
    "mainPage",
    "centerPage",
    "addCenter",
    "tabs",
    "centerInfo",
    "imag",
    "loaction",
    "addServise",
    "timeWeek",
    "freeBox",
    "button2",
    "submit",
    "button3",
    "categories",
    "embedHtml"
  ],
  topPage: ["topPage"],
  mainPage: ["mainPage"],
  centerPage: ["centerPage"],
  addCenter: [
    "addCenter",
    "tabs",
    "centerInfo",
    "imag",
    "loaction",
    "addServise",
    "timeWeek",
    "freeBox",
    "button2",
    "submit",
    "button3"
  ],
  tabs: ["tabs", "centerInfo", "imag", "loaction", "addServise", "timeWeek"],
  centerInfo: ["centerInfo"],
  imag: ["imag"],
  loaction: ["loaction"],
  addServise: ["addServise"],
  timeWeek: ["timeWeek"],
  freeBox: ["freeBox", "button2", "submit", "button3"],
  button2: ["button2"],
  submit: ["submit"],
  button3: ["button3"],
  categories: ["categories"],
  embedHtml: ["embedHtml"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  topPage: typeof TopPage;
  mainPage: typeof MainPage;
  centerPage: typeof CenterPage;
  addCenter: typeof Modal;
  tabs: typeof AntdTabs;
  centerInfo: typeof CenterInfo;
  imag: typeof Imag;
  loaction: typeof Loaction;
  addServise: typeof AddServise;
  timeWeek: typeof TimeWeek;
  freeBox: "div";
  button2: typeof Button;
  submit: typeof Button;
  button3: typeof Button;
  categories: typeof ApiRequest;
  embedHtml: typeof Embed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMain__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMain__VariantsArgs;
    args?: PlasmicMain__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicMain__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicMain__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMain__ArgProps,
          internalVariantPropNames: PlasmicMain__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMain__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMain";
  } else {
    func.displayName = `PlasmicMain.${nodeName}`;
  }
  return func;
}

export const PlasmicMain = Object.assign(
  // Top-level PlasmicMain renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    topPage: makeNodeComponent("topPage"),
    mainPage: makeNodeComponent("mainPage"),
    centerPage: makeNodeComponent("centerPage"),
    addCenter: makeNodeComponent("addCenter"),
    tabs: makeNodeComponent("tabs"),
    centerInfo: makeNodeComponent("centerInfo"),
    imag: makeNodeComponent("imag"),
    loaction: makeNodeComponent("loaction"),
    addServise: makeNodeComponent("addServise"),
    timeWeek: makeNodeComponent("timeWeek"),
    freeBox: makeNodeComponent("freeBox"),
    button2: makeNodeComponent("button2"),
    submit: makeNodeComponent("submit"),
    button3: makeNodeComponent("button3"),
    categories: makeNodeComponent("categories"),
    embedHtml: makeNodeComponent("embedHtml"),

    // Metadata about props expected for PlasmicMain
    internalVariantProps: PlasmicMain__VariantProps,
    internalArgProps: PlasmicMain__ArgProps
  }
);

export default PlasmicMain;
/* prettier-ignore-end */
