/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qARqpE4p5tZmJuNxFbTaPz
// Component: BVIyToFh1miy

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import Header from "../../Header"; // plasmic-import: Ot6T4AzLOJkl/component
import { ApiRequest } from "@/fragment/components/api-request"; // plasmic-import: TUk6VD6AhbGJ/codeComponent
import Service2 from "../../Service2"; // plasmic-import: -12Fp4g9XO2-/component
import { TextCollapse } from "@/components/TextCollapse"; // plasmic-import: 4siMWQuiaqGI/codeComponent
import CheckboxGroup from "../../CheckboxGroup"; // plasmic-import: -LTmesN9vMxo/component
import Checkbox from "../../Checkbox"; // plasmic-import: 7eMtZduHzknK/component
import Button from "../../Button"; // plasmic-import: 2MRRFY7jUAge/component
import { _useGlobalVariants } from "../website_starter/plasmic"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectModule
import { _useStyleTokens } from "../website_starter/PlasmicStyleTokensProvider"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../website_starter/plasmic.module.css"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectcss
import sty from "./PlasmicPayment.module.css"; // plasmic-import: BVIyToFh1miy/css

import CircleIcon from "../website_starter/icons/PlasmicIcon__Circle"; // plasmic-import: 4RgfxZWAffAT/icon
import ChevronDownIcon from "../website_starter/icons/PlasmicIcon__ChevronDown"; // plasmic-import: cDVOBX0F9d9g/icon

createPlasmicElementProxy;

export type PlasmicPayment__VariantMembers = {};
export type PlasmicPayment__VariantsArgs = {};
type VariantPropType = keyof PlasmicPayment__VariantsArgs;
export const PlasmicPayment__VariantProps = new Array<VariantPropType>();

export type PlasmicPayment__ArgsType = {
  subcatgori?: any;
  center?: any;
  id?: string;
  jalali?: any;
  token?: string;
};
type ArgPropType = keyof PlasmicPayment__ArgsType;
export const PlasmicPayment__ArgProps = new Array<ArgPropType>(
  "subcatgori",
  "center",
  "id",
  "jalali",
  "token"
);

export type PlasmicPayment__OverridesType = {
  root?: Flex__<"div">;
  embedHtml?: Flex__<typeof Embed>;
  header?: Flex__<typeof Header>;
  basic?: Flex__<typeof ApiRequest>;
  service2?: Flex__<typeof Service2>;
  img?: Flex__<typeof PlasmicImg__>;
  textCollapse?: Flex__<typeof TextCollapse>;
  checkboxGroup?: Flex__<typeof CheckboxGroup>;
  option1?: Flex__<typeof Checkbox>;
  section?: Flex__<"section">;
  online?: Flex__<"div">;
  button?: Flex__<typeof Button>;
  inPerson?: Flex__<"div">;
  button2?: Flex__<typeof Button>;
};

export interface DefaultPaymentProps {
  subcatgori?: any;
  center?: any;
  id?: string;
  jalali?: any;
  token?: string;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPayment__RenderFunc(props: {
  variants: PlasmicPayment__VariantsArgs;
  args: PlasmicPayment__ArgsType;
  overrides: PlasmicPayment__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          token:
            "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiZXhwaXJlIjoxNzY0NTA2MjczfQ.A6wRqW0jMYVg_rZ4OMZ5oXrcOVwKq3BG4i_wmvKf_8A"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "rate",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.basic?.data?.result?.rating_avg;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return 3;
              }
              throw e;
            }
          })()
      },
      {
        path: "basic.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "basic.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "basic.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "button.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "service",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => ({})
      },
      {
        path: "year",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return (() => {
                function faToEn(str) {
                  return str.replace(/[۰-۹]/g, d =>
                    String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))
                  );
                }
                const faDate = new Date().toLocaleDateString("fa-IR", {
                  year: "numeric",
                  month: "2-digit"
                });
                const enDate = faToEn(faDate);
                const [year, month] = enDate.split("/").map(Number);
                const dateObj = {
                  year,
                  month
                };
                return dateObj;
              })();
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return {};
              }
              throw e;
            }
          })()
      },
      {
        path: "yearActive",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return (() => {
                function faToEn(str) {
                  return str.replace(/[۰-۹]/g, d =>
                    String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))
                  );
                }
                const faDate = new Date().toLocaleDateString("fa-IR", {
                  year: "numeric",
                  month: "2-digit"
                });
                const enDate = faToEn(faDate);
                const [year, month] = enDate.split("/").map(Number);
                const dateObj = {
                  year,
                  month
                };
                return dateObj;
              })();
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return {};
              }
              throw e;
            }
          })()
      },
      {
        path: "checkboxGroup.value",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          hasVariant(globalVariants, "screen", "mobileOnly")
            ? (() => {
                try {
                  return undefined;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()
            : (() => {
                try {
                  return (() => {
                    const paymentOptions = [
                      {
                        value: "online",
                        label: "پرداخت آنلاین",
                        description: "پرداخت فقط به صورت آنلاین امکان‌پذیر است."
                      },
                      {
                        value: "in_person",
                        label: "پرداخت حضوری",
                        description: "پرداخت فقط به صورت حضوری امکان‌پذیر است."
                      }
                    ];

                    function getPayments(method) {
                      if (method === "both") return paymentOptions;
                      return paymentOptions.filter(
                        item => item.value === method
                      );
                    }
                    return getPayments(
                      $state.basic.data.result.service.payment_method
                    )[0].value;
                  })();
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [];
                  }
                  throw e;
                }
              })()
      },
      {
        path: "option1[].isSelected",
        type: "private",
        variableType: "boolean"
      },
      {
        path: "button2.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <Embed
        data-plasmic-name={"embedHtml"}
        data-plasmic-override={overrides.embedHtml}
        className={classNames("__wab_instance", sty.embedHtml)}
        code={
          '<script src="https://cdn.jsdelivr.net/npm/jalaali-js/dist/jalaali.js"></script>\r\n'
        }
      />

      <Header
        data-plasmic-name={"header"}
        data-plasmic-override={overrides.header}
        className={classNames("__wab_instance", sty.header)}
        slot={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__oJqd
            )}
          >
            {
              "\u062a\u0627\u06cc\u06cc\u062f \u0648 \u067e\u0631\u062f\u0627\u062e\u062a"
            }
          </div>
        }
      />

      <div className={classNames(projectcss.all, sty.freeBox__vxiP)}>
        <ApiRequest
          data-plasmic-name={"basic"}
          data-plasmic-override={overrides.basic}
          className={classNames("__wab_instance", sty.basic)}
          config={(() => {
            try {
              return {
                headers: {
                  Authorization: `Bearer ${$props.token}`
                }
              };
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
          errorDisplay={null}
          loadingDisplay={null}
          method={"GET"}
          onError={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["basic", "error"]).apply(
              null,
              eventArgs
            );
          }}
          onLoading={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["basic", "loading"]).apply(
              null,
              eventArgs
            );
          }}
          onSuccess={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["basic", "data"]).apply(
              null,
              eventArgs
            );
          }}
          params={(() => {
            try {
              return {
                id: $props.id
              };
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
          shouldFetch={(() => {
            try {
              return $props.id != undefined && $props.id != "";
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })()}
          url={"https://sayban.darkube.app/webhook/reservations/payment"}
        >
          <div className={classNames(projectcss.all, sty.freeBox__sPnkG)}>
            <div className={classNames(projectcss.all, sty.freeBox__r7Ep)}>
              <div className={classNames(projectcss.all, sty.freeBox__tkgDg)}>
                <div className={classNames(projectcss.all, sty.freeBox__yyc5C)}>
                  <Service2
                    data-plasmic-name={"service2"}
                    data-plasmic-override={overrides.service2}
                    className={classNames("__wab_instance", sty.service2)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__pwWnA)}
                    >
                      <PlasmicImg__
                        data-plasmic-name={"img"}
                        data-plasmic-override={overrides.img}
                        alt={""}
                        className={classNames(sty.img)}
                        displayHeight={"3rem"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"3rem"}
                        loading={"lazy"}
                        src={(() => {
                          try {
                            return $state.basic?.data?.result?.main_image;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return {
                                src: "/plasmic/website_starter/images/image6.png",
                                fullWidth: 224,
                                fullHeight: 224,
                                aspectRatio: undefined
                              };
                            }
                            throw e;
                          }
                        })()}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rl6On
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gw2Ub
                          )}
                        >
                          <React.Fragment>
                            {$state.basic?.data?.result?.name || ""}
                          </React.Fragment>
                        </div>
                        <TextCollapse
                          data-plasmic-name={"textCollapse"}
                          data-plasmic-override={overrides.textCollapse}
                          className={classNames(
                            "__wab_instance",
                            sty.textCollapse
                          )}
                          enableToggle={true}
                          maxLines={1}
                          text={(() => {
                            try {
                              return (
                                $state.basic?.data?.result?.description || ""
                              );
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                        />
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xjO3C
                      )}
                    >
                      {""}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__isyyg)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wmvnl
                        )}
                      >
                        <div
                          className={projectcss.__wab_expr_html_text}
                          dangerouslySetInnerHTML={{
                            __html: (() => {
                              const startRaw =
                                $state?.basic?.data?.result?.payment
                                  ?.start_time;
                              const endRaw =
                                $state?.basic?.data?.result?.payment?.end_time;
                              const start = startRaw
                                ? new Date(startRaw)
                                : null;
                              const end = endRaw ? new Date(endRaw) : null;
                              let persianDate = "-";
                              let startTime = "-";
                              let endTime = "-";
                              const isValidDate = d =>
                                d instanceof Date &&
                                d.toString() !== "Invalid Date";
                              if (isValidDate(start)) {
                                persianDate = new Intl.DateTimeFormat("fa-IR", {
                                  weekday: "long",
                                  day: "numeric",
                                  month: "long"
                                }).format(start);
                                startTime = start.toLocaleTimeString("fa-IR", {
                                  hour: "numeric",
                                  minute: "2-digit"
                                });
                              }
                              if (isValidDate(end)) {
                                endTime = end.toLocaleTimeString("fa-IR", {
                                  hour: "numeric",
                                  minute: "2-digit"
                                });
                              }
                              const serviceName =
                                $state?.basic?.data?.result?.service?.name ||
                                "سرویس نامشخص";
                              const message = `
شما ${serviceName} را انتخاب کرده‌اید.
<span class="BoldText">زمان انتخابی: ${persianDate} | از ساعت ${startTime} تا ${endTime}</span>
لطفاً جهت نهایی‌سازی رزرو، پرداخت را انجام دهید.
`;
                              return message;
                            })()
                          }}
                        />
                      </div>
                    </div>
                  </Service2>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y1PF
                  )}
                >
                  {""}
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__pnxjD)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__bC6ZC)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kt5M7)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kOkUb
                        )}
                      >
                        {
                          "\u0631\u0648\u0634 \u067e\u0631\u062f\u0627\u062e\u062a"
                        }
                      </div>
                    </div>
                    <CheckboxGroup
                      data-plasmic-name={"checkboxGroup"}
                      data-plasmic-override={overrides.checkboxGroup}
                      className={classNames(
                        "__wab_instance",
                        sty.checkboxGroup
                      )}
                      onChange={async (...eventArgs: any) => {
                        generateStateOnChangeProp($state, [
                          "checkboxGroup",
                          "value"
                        ]).apply(null, eventArgs);

                        if (
                          eventArgs.length > 1 &&
                          eventArgs[1] &&
                          eventArgs[1]._plasmic_state_init_
                        ) {
                          return;
                        }

                        (async val => {
                          const $steps = {};

                          $steps["updateCheckboxGroupValue"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["checkboxGroup", "value"]
                                  },
                                  operation: 0
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateCheckboxGroupValue"] != null &&
                            typeof $steps["updateCheckboxGroupValue"] ===
                              "object" &&
                            typeof $steps["updateCheckboxGroupValue"].then ===
                              "function"
                          ) {
                            $steps["updateCheckboxGroupValue"] =
                              await $steps["updateCheckboxGroupValue"];
                          }
                        }).apply(null, eventArgs);
                      }}
                      options={(_par =>
                        !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                        (() => {
                          try {
                            return (() => {
                              const paymentOptions = [
                                {
                                  value: "online",
                                  label: "پرداخت آنلاین",
                                  description:
                                    "پرداخت فقط به صورت آنلاین امکان‌پذیر است."
                                },
                                {
                                  value: "in_person",
                                  label: "پرداخت حضوری",
                                  description:
                                    "پرداخت فقط به صورت حضوری امکان‌پذیر است."
                                }
                              ];

                              function getPayments(method) {
                                if (method === "both") return paymentOptions;
                                return paymentOptions.filter(
                                  item => item.value === method
                                );
                              }
                              return getPayments(
                                $state.basic.data.result.service.payment_method
                              );
                            })();
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return [];
                            }
                            throw e;
                          }
                        })()
                      ).map((__plasmic_item_0, __plasmic_idx_0) => {
                        const currentItem = __plasmic_item_0;
                        const currentIndex = __plasmic_idx_0;
                        return (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__lQ8Ia
                            )}
                            key={currentIndex}
                          >
                            {(() => {
                              const child$Props = {
                                className: classNames(
                                  "__wab_instance",
                                  sty.option1
                                ),
                                icon: (() => {
                                  try {
                                    return currentItem.value;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })(),
                                isSelected: generateStateValueProp($state, [
                                  "option1",
                                  __plasmic_idx_0,
                                  "isSelected"
                                ]),
                                label: (
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__xa1Le
                                    )}
                                  >
                                    <React.Fragment>
                                      {(() => {
                                        try {
                                          return currentItem.label;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return "Option 1";
                                          }
                                          throw e;
                                        }
                                      })()}
                                    </React.Fragment>
                                  </div>
                                ),
                                onChange: async (...eventArgs: any) => {
                                  generateStateOnChangeProp($state, [
                                    "option1",
                                    __plasmic_idx_0,
                                    "isSelected"
                                  ]).apply(null, eventArgs);

                                  if (
                                    eventArgs.length > 1 &&
                                    eventArgs[1] &&
                                    eventArgs[1]._plasmic_state_init_
                                  ) {
                                    return;
                                  }
                                },
                                shape: "circle",
                                value: hasVariant(
                                  globalVariants,
                                  "screen",
                                  "mobileOnly"
                                )
                                  ? (() => {
                                      try {
                                        return currentItem.value;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return undefined;
                                        }
                                        throw e;
                                      }
                                    })()
                                  : (() => {
                                      try {
                                        return currentItem.value;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return undefined;
                                        }
                                        throw e;
                                      }
                                    })()
                              };

                              initializePlasmicStates(
                                $state,
                                [
                                  {
                                    name: "option1[].isSelected",
                                    initFunc: ({ $props, $state, $queries }) =>
                                      false
                                  }
                                ],
                                [__plasmic_idx_0]
                              );
                              return (
                                <Checkbox
                                  data-plasmic-name={"option1"}
                                  data-plasmic-override={overrides.option1}
                                  {...child$Props}
                                >
                                  <React.Fragment>
                                    {currentItem.description}
                                  </React.Fragment>
                                </Checkbox>
                              );
                            })()}
                            {(() => {
                              try {
                                return true;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return true;
                                }
                                throw e;
                              }
                            })() ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__rItN4
                                )}
                              >
                                {""}
                              </div>
                            ) : null}
                          </div>
                        );
                      })}
                      showLabel={false}
                      value={generateStateValueProp($state, [
                        "checkboxGroup",
                        "value"
                      ])}
                    />
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lDrs
                    )}
                  >
                    {""}
                  </div>
                  {(() => {
                    try {
                      return $state.basic?.data?.result;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return true;
                      }
                      throw e;
                    }
                  })() ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___7Gvtq
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__iosbS
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__iSeVj
                          )}
                        >
                          {"\u0635\u0648\u0631\u062a \u062d\u0633\u0627\u0628"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___20XYm
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__hkMkW
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__k5I6Q
                            )}
                          >
                            {
                              "\u062c\u0645\u0639 \u0627\u0642\u0644\u0627\u0645"
                            }
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rFkVw
                            )}
                          >
                            <React.Fragment>
                              {$state.basic.data.result.service?.final_price?.toLocaleString() +
                                " تومان"}
                            </React.Fragment>
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___7IhOz
                          )}
                        >
                          {""}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___83XI4
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__iGbfx
                            )}
                          >
                            {
                              "\u0645\u0628\u0644\u063a \u0642\u0627\u0628\u0644 \u067e\u0631\u062f\u0627\u062e\u062a"
                            }
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__lpbty
                            )}
                          >
                            <React.Fragment>
                              {$state.basic.data.result.service?.final_price?.toLocaleString() +
                                " تومان"}
                            </React.Fragment>
                          </div>
                        </div>
                      </div>
                    </div>
                  ) : null}
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aygH9
                    )}
                  >
                    {""}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section, "page")}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__aGBz1
              )}
            >
              {""}
            </div>
            {(() => {
              try {
                return $state.checkboxGroup.value == "online";
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                data-plasmic-name={"online"}
                data-plasmic-override={overrides.online}
                className={classNames(projectcss.all, sty.online)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__hilZ)}>
                  {(() => {
                    try {
                      return (
                        $state.basic?.data?.result?.service.discount_percent !=
                          0 &&
                        $state.basic?.data?.result?.service.discount_percent !=
                          null
                      );
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return true;
                      }
                      throw e;
                    }
                  })() ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kxWEm)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__l1Hht
                        )}
                      >
                        <React.Fragment>
                          {$state.basic?.data?.result?.service.price?.toLocaleString() +
                            " تومان"}
                        </React.Fragment>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___6ZQ8K
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__u00Cj
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return (
                                  $state.basic?.data?.result?.service
                                    .discount_percent + "%"
                                );
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "1";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                    </div>
                  ) : null}
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__e1XGo
                    )}
                  >
                    <React.Fragment>
                      {$state.basic?.data?.result?.service?.final_price?.toLocaleString() +
                        " تومان"}
                    </React.Fragment>
                  </div>
                </div>
                <Button
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames("__wab_instance", sty.button)}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__s4RNp
                      )}
                    >
                      {"\u067e\u0631\u062f\u0627\u062e\u062a"}
                    </div>
                  }
                  loading={generateStateValueProp($state, [
                    "button",
                    "loading"
                  ])}
                  onClick={async event => {
                    const $steps = {};

                    $steps["runCode"] = true
                      ? (() => {
                          const actionArgs = {
                            customFunction: async () => {
                              return ($state.button.loading = true);
                            }
                          };
                          return (({ customFunction }) => {
                            return customFunction();
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["runCode"] != null &&
                      typeof $steps["runCode"] === "object" &&
                      typeof $steps["runCode"].then === "function"
                    ) {
                      $steps["runCode"] = await $steps["runCode"];
                    }

                    $steps["invokeGlobalAction"] = true
                      ? (() => {
                          const actionArgs = {
                            args: [
                              "POST",
                              "https://sayban.darkube.app/webhook/reservations/update",
                              undefined,
                              (() => {
                                try {
                                  return {
                                    id: $props.id,
                                    payment_status: "unpaid",
                                    payment_method: $state.checkboxGroup.value,
                                    status: "pending"
                                  };
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return undefined;
                                  }
                                  throw e;
                                }
                              })(),
                              (() => {
                                try {
                                  return {
                                    headers: {
                                      Authorization: `Bearer ${$props.token}`
                                    }
                                  };
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return undefined;
                                  }
                                  throw e;
                                }
                              })()
                            ]
                          };
                          return $globalActions["Fragment.apiRequest"]?.apply(
                            null,
                            [...actionArgs.args]
                          );
                        })()
                      : undefined;
                    if (
                      $steps["invokeGlobalAction"] != null &&
                      typeof $steps["invokeGlobalAction"] === "object" &&
                      typeof $steps["invokeGlobalAction"].then === "function"
                    ) {
                      $steps["invokeGlobalAction"] =
                        await $steps["invokeGlobalAction"];
                    }

                    $steps["runCode2"] = true
                      ? (() => {
                          const actionArgs = {
                            customFunction: async () => {
                              return ($state.button.loading = false);
                            }
                          };
                          return (({ customFunction }) => {
                            return customFunction();
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["runCode2"] != null &&
                      typeof $steps["runCode2"] === "object" &&
                      typeof $steps["runCode2"].then === "function"
                    ) {
                      $steps["runCode2"] = await $steps["runCode2"];
                    }
                  }}
                  onLoadingChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "button",
                      "loading"
                    ]).apply(null, eventArgs);

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  }}
                />
              </div>
            ) : null}
            {(() => {
              try {
                return $state.checkboxGroup.value == "in_person";
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                data-plasmic-name={"inPerson"}
                data-plasmic-override={overrides.inPerson}
                className={classNames(projectcss.all, sty.inPerson)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__vWvh7)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jYNaO
                    )}
                  >
                    <React.Fragment>
                      {"هزینه به‌صورت حضوری دریافت می‌شود."}
                    </React.Fragment>
                  </div>
                </div>
                <Button
                  data-plasmic-name={"button2"}
                  data-plasmic-override={overrides.button2}
                  className={classNames("__wab_instance", sty.button2)}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jHJv
                      )}
                    >
                      {"\u0631\u0632\u0631\u0648 \u0632\u0645\u0627\u0646"}
                    </div>
                  }
                  loading={generateStateValueProp($state, [
                    "button2",
                    "loading"
                  ])}
                  onLoadingChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "button2",
                      "loading"
                    ]).apply(null, eventArgs);

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  }}
                />
              </div>
            ) : null}
          </section>
        </ApiRequest>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "embedHtml",
    "header",
    "basic",
    "service2",
    "img",
    "textCollapse",
    "checkboxGroup",
    "option1",
    "section",
    "online",
    "button",
    "inPerson",
    "button2"
  ],
  embedHtml: ["embedHtml"],
  header: ["header"],
  basic: [
    "basic",
    "service2",
    "img",
    "textCollapse",
    "checkboxGroup",
    "option1",
    "section",
    "online",
    "button",
    "inPerson",
    "button2"
  ],
  service2: ["service2", "img", "textCollapse"],
  img: ["img"],
  textCollapse: ["textCollapse"],
  checkboxGroup: ["checkboxGroup", "option1"],
  option1: ["option1"],
  section: ["section", "online", "button", "inPerson", "button2"],
  online: ["online", "button"],
  button: ["button"],
  inPerson: ["inPerson", "button2"],
  button2: ["button2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  embedHtml: typeof Embed;
  header: typeof Header;
  basic: typeof ApiRequest;
  service2: typeof Service2;
  img: typeof PlasmicImg__;
  textCollapse: typeof TextCollapse;
  checkboxGroup: typeof CheckboxGroup;
  option1: typeof Checkbox;
  section: "section";
  online: "div";
  button: typeof Button;
  inPerson: "div";
  button2: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPayment__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPayment__VariantsArgs;
    args?: PlasmicPayment__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPayment__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPayment__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPayment__ArgProps,
          internalVariantPropNames: PlasmicPayment__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPayment__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPayment";
  } else {
    func.displayName = `PlasmicPayment.${nodeName}`;
  }
  return func;
}

export const PlasmicPayment = Object.assign(
  // Top-level PlasmicPayment renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    embedHtml: makeNodeComponent("embedHtml"),
    header: makeNodeComponent("header"),
    basic: makeNodeComponent("basic"),
    service2: makeNodeComponent("service2"),
    img: makeNodeComponent("img"),
    textCollapse: makeNodeComponent("textCollapse"),
    checkboxGroup: makeNodeComponent("checkboxGroup"),
    option1: makeNodeComponent("option1"),
    section: makeNodeComponent("section"),
    online: makeNodeComponent("online"),
    button: makeNodeComponent("button"),
    inPerson: makeNodeComponent("inPerson"),
    button2: makeNodeComponent("button2"),

    // Metadata about props expected for PlasmicPayment
    internalVariantProps: PlasmicPayment__VariantProps,
    internalArgProps: PlasmicPayment__ArgProps
  }
);

export default PlasmicPayment;
/* prettier-ignore-end */
