/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qARqpE4p5tZmJuNxFbTaPz
// Component: 3LWfoc10rUWe

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: 2MRRFY7jUAge/component
import TextInput from "../../TextInput"; // plasmic-import: lMgENIWzjnK0/component
import Check from "../../Check"; // plasmic-import: jHhGioxaI9lI/component
import ItemShow from "../../ItemShow"; // plasmic-import: hegjECXSYJcF/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicQuestionItem2.module.css"; // plasmic-import: 3LWfoc10rUWe/css

import HelpSquareRoundedFilledIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__HelpSquareRoundedFilled"; // plasmic-import: Y3EQxr0UdrjQ/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 4RgfxZWAffAT/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: cDVOBX0F9d9g/icon
import Icon58Icon from "./icons/PlasmicIcon__Icon58"; // plasmic-import: ZZecBkDFVPaA/icon
import Icon10Icon from "./icons/PlasmicIcon__Icon10"; // plasmic-import: MSkuAHzkec39/icon
import PlusIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__Plus"; // plasmic-import: _pdhShvRj8aO/icon

createPlasmicElementProxy;

export type PlasmicQuestionItem2__VariantMembers = {};
export type PlasmicQuestionItem2__VariantsArgs = {};
type VariantPropType = keyof PlasmicQuestionItem2__VariantsArgs;
export const PlasmicQuestionItem2__VariantProps = new Array<VariantPropType>();

export type PlasmicQuestionItem2__ArgsType = {
  currentItem?: any;
  currentIndex?: any;
  onDelet?: (event: any) => void;
};
type ArgPropType = keyof PlasmicQuestionItem2__ArgsType;
export const PlasmicQuestionItem2__ArgProps = new Array<ArgPropType>(
  "currentItem",
  "currentIndex",
  "onDelet"
);

export type PlasmicQuestionItem2__OverridesType = {
  root?: Flex__<"div">;
  button?: Flex__<typeof Button>;
  textInput?: Flex__<typeof TextInput>;
  check?: Flex__<typeof Check>;
  check2?: Flex__<typeof Check>;
  check4?: Flex__<typeof Check>;
  check3?: Flex__<typeof Check>;
  itemShow?: Flex__<typeof ItemShow>;
  textInput2?: Flex__<typeof TextInput>;
  button3?: Flex__<typeof Button>;
  check5?: Flex__<typeof Check>;
};

export interface DefaultQuestionItem2Props {
  currentItem?: any;
  currentIndex?: any;
  onDelet?: (event: any) => void;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicQuestionItem2__RenderFunc(props: {
  variants: PlasmicQuestionItem2__VariantsArgs;
  args: PlasmicQuestionItem2__ArgsType;
  overrides: PlasmicQuestionItem2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $props?.currentItem?.question_text || "";
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "check.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props.currentItem?.is_required
      },
      {
        path: "check2.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props.currentItem?.requires_date
      },
      {
        path: "check3.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props.currentItem?.requires_address
      },
      {
        path: "check4.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props.currentItem?.requires_time
      },
      {
        path: "check5.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "button3.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "textInput2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "showInput",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "opshen",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return JSON.parse($props.currentItem?.options || "[]");
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()
      },
      {
        path: "button.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );

  const $globalActions = useGlobalActions?.();

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_qARqpE4p5tZmJuNxFbTaPz",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames("all", sty.freeBox__usyly)}>
        <div className={classNames("all", sty.freeBox__hb0RY)}>
          <HelpSquareRoundedFilledIcon
            className={classNames("all", sty.svg__ptzY)}
            role={"img"}
          />

          <div className={classNames("all", "__wab_text", sty.text__byub4)}>
            <React.Fragment>
              {(() => {
                try {
                  return "سوال " + ($props.currentIndex + 1);
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "\u0633\u0648\u0627\u0644\u0627\u062a";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
          <Button
            data-plasmic-name={"button"}
            data-plasmic-override={overrides.button}
            className={classNames("__wab_instance", sty.button)}
            color={"neutral"}
            label={
              <div className={classNames("all", "__wab_text", sty.text__ihrYg)}>
                {"\u0628\u0631\u0648\u0632\u0631\u0633\u0627\u0646\u06cc"}
              </div>
            }
            loading={generateStateValueProp($state, ["button", "loading"])}
            onClick={async event => {
              const $steps = {};

              $steps["updateButtonLoading"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["button", "loading"]
                      },
                      operation: 4
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      const oldValue = $stateGet(objRoot, variablePath);
                      $stateSet(objRoot, variablePath, !oldValue);
                      return !oldValue;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateButtonLoading"] != null &&
                typeof $steps["updateButtonLoading"] === "object" &&
                typeof $steps["updateButtonLoading"].then === "function"
              ) {
                $steps["updateButtonLoading"] =
                  await $steps["updateButtonLoading"];
              }

              $steps["invokeGlobalAction"] = true
                ? (() => {
                    const actionArgs = {
                      args: [
                        "POST",
                        "/panel/question/update",
                        undefined,
                        {
                          id: $props.currentItem.id,
                          question_text: $state.textInput.value,
                          is_required: $state.check.isSelected,
                          requires_date: $state.check2.isSelected,
                          requires_time: $state.check4.isSelected,
                          requires_address: $state.check3.isSelected,
                          options: JSON.stringify($state.opshen),
                          allow_multiple: $state.check5.isSelected
                        }
                      ]
                    };
                    return $globalActions["Fragment.apiRequest"]?.apply(null, [
                      ...actionArgs.args
                    ]);
                  })()
                : undefined;
              if (
                $steps["invokeGlobalAction"] != null &&
                typeof $steps["invokeGlobalAction"] === "object" &&
                typeof $steps["invokeGlobalAction"].then === "function"
              ) {
                $steps["invokeGlobalAction"] =
                  await $steps["invokeGlobalAction"];
              }

              $steps["invokeGlobalAction2"] = $steps.invokeGlobalAction?.data
                ?.message
                ? (() => {
                    const actionArgs = {
                      args: [
                        $steps.invokeGlobalAction.data.success
                          ? "success"
                          : "error",
                        (() => {
                          try {
                            return $steps.invokeGlobalAction.data.message;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })(),
                        "top-center"
                      ]
                    };
                    return $globalActions["Fragment.showToast"]?.apply(null, [
                      ...actionArgs.args
                    ]);
                  })()
                : undefined;
              if (
                $steps["invokeGlobalAction2"] != null &&
                typeof $steps["invokeGlobalAction2"] === "object" &&
                typeof $steps["invokeGlobalAction2"].then === "function"
              ) {
                $steps["invokeGlobalAction2"] =
                  await $steps["invokeGlobalAction2"];
              }

              $steps["updateButtonLoading2"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["button", "loading"]
                      },
                      operation: 4
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      const oldValue = $stateGet(objRoot, variablePath);
                      $stateSet(objRoot, variablePath, !oldValue);
                      return !oldValue;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateButtonLoading2"] != null &&
                typeof $steps["updateButtonLoading2"] === "object" &&
                typeof $steps["updateButtonLoading2"].then === "function"
              ) {
                $steps["updateButtonLoading2"] =
                  await $steps["updateButtonLoading2"];
              }
            }}
            onLoadingChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["button", "loading"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
          />

          <div
            className={classNames("all", sty.freeBox__herd8)}
            onClick={args.onDelet}
          >
            <Icon58Icon
              className={classNames("all", sty.svg__axwUm)}
              role={"img"}
            />
          </div>
        </div>
        <div className={classNames("all", sty.freeBox__b4WW, "dark")}>
          <TextInput
            data-plasmic-name={"textInput"}
            data-plasmic-override={overrides.textInput}
            className={classNames("__wab_instance", sty.textInput)}
            onChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["textInput", "value"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            placeholder={"\u0645\u062a\u0646 \u067e\u0631\u0633\u0634"}
            type={"lineBoxDark"}
            value={generateStateValueProp($state, ["textInput", "value"])}
          />

          <Check
            data-plasmic-name={"check"}
            data-plasmic-override={overrides.check}
            className={classNames("__wab_instance", sty.check)}
            isSelected={generateStateValueProp($state, ["check", "isSelected"])}
            label={
              <div className={classNames("all", "__wab_text", sty.text__tQmPf)}>
                {
                  "\u0622\u06cc\u0627 \u067e\u0627\u0633\u062e \u0628\u0647 \u0627\u06cc\u0646 \u0633\u0648\u0627\u0644 \u0627\u062c\u0628\u0627\u0631\u06cc \u0627\u0633\u062a\u061f"
                }
              </div>
            }
            onChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["check", "isSelected"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
          />

          <Check
            data-plasmic-name={"check2"}
            data-plasmic-override={overrides.check2}
            className={classNames("__wab_instance", sty.check2)}
            isSelected={generateStateValueProp($state, [
              "check2",
              "isSelected"
            ])}
            label={
              <div
                className={classNames("all", "__wab_text", sty.text___62JnP)}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      "\u0622\u06cc\u0627 \u0627\u06cc\u0646 \u0633\u0648\u0627\u0644 \u0646\u06cc\u0627\u0632 \u0628\u0647 \u062f\u0631\u06cc\u0627\u0641\u062a "
                    }
                  </React.Fragment>
                  <span
                    className={
                      "plasmic_default__all plasmic_default__span plasmic_default__span__qARqp"
                    }
                    style={{ color: "#505F3A", fontWeight: 700 }}
                  >
                    {"\u00ab\u062a\u0627\u0631\u06cc\u062e\u00bb"}
                  </span>
                  <React.Fragment>
                    {" \u062f\u0627\u0631\u062f\u061f"}
                  </React.Fragment>
                </React.Fragment>
              </div>
            }
            onChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["check2", "isSelected"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
          />

          <Check
            data-plasmic-name={"check4"}
            data-plasmic-override={overrides.check4}
            className={classNames("__wab_instance", sty.check4)}
            isSelected={generateStateValueProp($state, [
              "check4",
              "isSelected"
            ])}
            label={
              <div
                className={classNames("all", "__wab_text", sty.text___0Xosk)}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      "\u0622\u06cc\u0627 \u0627\u06cc\u0646 \u0633\u0648\u0627\u0644 \u0646\u06cc\u0627\u0632 \u0628\u0647 \u062f\u0631\u06cc\u0627\u0641\u062a "
                    }
                  </React.Fragment>
                  <span
                    className={
                      "plasmic_default__all plasmic_default__span plasmic_default__span__qARqp"
                    }
                    style={{ color: "#4F5B2A", fontWeight: 700 }}
                  >
                    {"\u00ab\u0632\u0645\u0627\u0646\u00bb"}
                  </span>
                  <React.Fragment>
                    {" \u062f\u0627\u0631\u062f\u061f"}
                  </React.Fragment>
                </React.Fragment>
              </div>
            }
            onChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["check4", "isSelected"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
          />

          <Check
            data-plasmic-name={"check3"}
            data-plasmic-override={overrides.check3}
            className={classNames("__wab_instance", sty.check3)}
            isSelected={generateStateValueProp($state, [
              "check3",
              "isSelected"
            ])}
            label={
              <div className={classNames("all", "__wab_text", sty.text__gpsxI)}>
                <React.Fragment>
                  <React.Fragment>
                    {
                      "\u0622\u06cc\u0627 \u0627\u06cc\u0646 \u0633\u0648\u0627\u0644 \u0646\u06cc\u0627\u0632 \u0628\u0647 \u062f\u0631\u06cc\u0627\u0641\u062a "
                    }
                  </React.Fragment>
                  <span
                    className={
                      "plasmic_default__all plasmic_default__span plasmic_default__span__qARqp"
                    }
                    style={{ color: "#4F5B2A", fontWeight: 700 }}
                  >
                    {"\u00ab\u0622\u062f\u0631\u0633\u00bb"}
                  </span>
                  <React.Fragment>
                    {" \u062f\u0627\u0631\u062f\u061f"}
                  </React.Fragment>
                </React.Fragment>
              </div>
            }
            onChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["check3", "isSelected"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
          />

          <div className={classNames("all", sty.freeBox__cxGI)}>
            {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
              (() => {
                try {
                  return $state.opshen;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [];
                  }
                  throw e;
                }
              })()
            ).map((__plasmic_item_0, __plasmic_idx_0) => {
              const currentItem = __plasmic_item_0;
              const currentIndex = __plasmic_idx_0;
              return (
                <ItemShow
                  data-plasmic-name={"itemShow"}
                  data-plasmic-override={overrides.itemShow}
                  className={classNames("__wab_instance", sty.itemShow)}
                  key={currentIndex}
                  ligtht={true}
                  select={true}
                  slot={
                    <Icon10Icon
                      className={classNames("all", sty.svg___7NhR7)}
                      onClick={async event => {
                        const $steps = {};

                        $steps["runCode"] = true
                          ? (() => {
                              const actionArgs = {
                                customFunction: async () => {
                                  return ($state.opshen = $state.opshen.filter(
                                    i => i != currentItem
                                  ));
                                }
                              };
                              return (({ customFunction }) => {
                                return customFunction();
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["runCode"] != null &&
                          typeof $steps["runCode"] === "object" &&
                          typeof $steps["runCode"].then === "function"
                        ) {
                          $steps["runCode"] = await $steps["runCode"];
                        }
                      }}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__aBgMs)}
                  >
                    <React.Fragment>{currentItem}</React.Fragment>
                  </div>
                </ItemShow>
              );
            })}
            {(() => {
              try {
                return $state.showInput;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <TextInput
                data-plasmic-name={"textInput2"}
                data-plasmic-override={overrides.textInput2}
                ariaInputOnBlur={async focusEvent => {
                  const $steps = {};

                  $steps["runCode"] = true
                    ? (() => {
                        const actionArgs = {
                          customFunction: async () => {
                            return (() => {
                              $state.opshen.push($state.textInput2.value);
                              $state.showInput = false;
                              return ($state.textInput2.value = "");
                            })();
                          }
                        };
                        return (({ customFunction }) => {
                          return customFunction();
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["runCode"] != null &&
                    typeof $steps["runCode"] === "object" &&
                    typeof $steps["runCode"].then === "function"
                  ) {
                    $steps["runCode"] = await $steps["runCode"];
                  }
                }}
                className={classNames("__wab_instance", sty.textInput2)}
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "textInput2",
                    "value"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                style2={"rounded"}
                type={"soft"}
                value={generateStateValueProp($state, ["textInput2", "value"])}
              />
            ) : null}
            <Button
              data-plasmic-name={"button3"}
              data-plasmic-override={overrides.button3}
              className={classNames("__wab_instance", sty.button3)}
              color={"success"}
              iconStart={true}
              label={
                <div
                  className={classNames("all", "__wab_text", sty.text__f9157)}
                >
                  {
                    "\u0627\u0641\u0632\u0648\u062f\u0646 \u06af\u0632\u06cc\u0646\u0647"
                  }
                </div>
              }
              loading={generateStateValueProp($state, ["button3", "loading"])}
              onClick={async event => {
                const $steps = {};

                $steps["updateShowInput"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["showInput"]
                        },
                        operation: 0,
                        value: true
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateShowInput"] != null &&
                  typeof $steps["updateShowInput"] === "object" &&
                  typeof $steps["updateShowInput"].then === "function"
                ) {
                  $steps["updateShowInput"] = await $steps["updateShowInput"];
                }
              }}
              onLoadingChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, ["button3", "loading"]).apply(
                  null,
                  eventArgs
                );

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              roundedFull={true}
              start={
                <PlusIcon
                  className={classNames("all", sty.svg__oFfJ)}
                  role={"img"}
                />
              }
            />
          </div>
          <Check
            data-plasmic-name={"check5"}
            data-plasmic-override={overrides.check5}
            className={classNames("__wab_instance", sty.check5)}
            isSelected={generateStateValueProp($state, [
              "check5",
              "isSelected"
            ])}
            label={
              <div className={classNames("all", "__wab_text", sty.text__tHp2M)}>
                {
                  "\u0622\u06cc\u0627 \u0627\u06cc\u0646 \u0633\u0648\u0627\u0644 \u0686\u0646\u062f \u0627\u0646\u062a\u062e\u0627\u0628\u06cc \u0627\u0633\u062a\u061f"
                }
              </div>
            }
            onChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["check5", "isSelected"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
          />
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "button",
    "textInput",
    "check",
    "check2",
    "check4",
    "check3",
    "itemShow",
    "textInput2",
    "button3",
    "check5"
  ],
  button: ["button"],
  textInput: ["textInput"],
  check: ["check"],
  check2: ["check2"],
  check4: ["check4"],
  check3: ["check3"],
  itemShow: ["itemShow"],
  textInput2: ["textInput2"],
  button3: ["button3"],
  check5: ["check5"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  button: typeof Button;
  textInput: typeof TextInput;
  check: typeof Check;
  check2: typeof Check;
  check4: typeof Check;
  check3: typeof Check;
  itemShow: typeof ItemShow;
  textInput2: typeof TextInput;
  button3: typeof Button;
  check5: typeof Check;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicQuestionItem2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicQuestionItem2__VariantsArgs;
    args?: PlasmicQuestionItem2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicQuestionItem2__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicQuestionItem2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicQuestionItem2__ArgProps,
          internalVariantPropNames: PlasmicQuestionItem2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicQuestionItem2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicQuestionItem2";
  } else {
    func.displayName = `PlasmicQuestionItem2.${nodeName}`;
  }
  return func;
}

export const PlasmicQuestionItem2 = Object.assign(
  // Top-level PlasmicQuestionItem2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    button: makeNodeComponent("button"),
    textInput: makeNodeComponent("textInput"),
    check: makeNodeComponent("check"),
    check2: makeNodeComponent("check2"),
    check4: makeNodeComponent("check4"),
    check3: makeNodeComponent("check3"),
    itemShow: makeNodeComponent("itemShow"),
    textInput2: makeNodeComponent("textInput2"),
    button3: makeNodeComponent("button3"),
    check5: makeNodeComponent("check5"),

    // Metadata about props expected for PlasmicQuestionItem2
    internalVariantProps: PlasmicQuestionItem2__VariantProps,
    internalArgProps: PlasmicQuestionItem2__ArgProps
  }
);

export default PlasmicQuestionItem2;
/* prettier-ignore-end */
