/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qARqpE4p5tZmJuNxFbTaPz
// Component: gJ_VOn2U5Tvp

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: 2MRRFY7jUAge/component
import Select from "../../Select"; // plasmic-import: IQ4yTzxYcpjO/component
import MenuItem from "../../MenuItem"; // plasmic-import: fC_9RAtGrwae/component
import MenuSection from "../../MenuSection"; // plasmic-import: PvgERH0q4dKA/component
import { ApiRequest } from "@/fragment/components/api-request"; // plasmic-import: TUk6VD6AhbGJ/codeComponent
import Errorpage from "../../Errorpage"; // plasmic-import: HTnfDJNIbaau/component
import EmptyPage from "../../EmptyPage"; // plasmic-import: q5YsvjSR6-JD/component
import QuestionItem2 from "../../QuestionItem2"; // plasmic-import: 3LWfoc10rUWe/component
import Snackbar from "../../Snackbar"; // plasmic-import: CaodI8ra68z4/component
import { AntdModal } from "@plasmicpkgs/antd5/skinny/registerModal";
import QuestionItemModal from "../../QuestionItemModal"; // plasmic-import: A0O5IJQKxt_v/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicMainPageQuestion.module.css"; // plasmic-import: gJ_VOn2U5Tvp/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 4RgfxZWAffAT/icon
import Icon56Icon from "./icons/PlasmicIcon__Icon56"; // plasmic-import: 9uSUOFbEcoV4/icon
import Icon115Icon from "./icons/PlasmicIcon__Icon115"; // plasmic-import: K82EqXtBnJoL/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: cDVOBX0F9d9g/icon

createPlasmicElementProxy;

export type PlasmicMainPageQuestion__VariantMembers = {};
export type PlasmicMainPageQuestion__VariantsArgs = {};
type VariantPropType = keyof PlasmicMainPageQuestion__VariantsArgs;
export const PlasmicMainPageQuestion__VariantProps =
  new Array<VariantPropType>();

export type PlasmicMainPageQuestion__ArgsType = {
  openEdit?: (event: any) => void;
  categpty?: any;
  onCategptyChange?: (val: string) => void;
  onRowClicked?: (rowKey: string, row: any, event: any) => void;
  centerDelete?: () => void;
  onCenterChange?: (val: string) => void;
  restart?: string;
  onRestartChange?: (val: string) => void;
  list?: boolean;
  onListChange2?: (val: string) => void;
  state?: string;
  addService?: (event: any) => void;
  rule?: string;
  selected?: any;
  onSelectedChange?: (val: string) => void;
};
type ArgPropType = keyof PlasmicMainPageQuestion__ArgsType;
export const PlasmicMainPageQuestion__ArgProps = new Array<ArgPropType>(
  "openEdit",
  "categpty",
  "onCategptyChange",
  "onRowClicked",
  "centerDelete",
  "onCenterChange",
  "restart",
  "onRestartChange",
  "list",
  "onListChange2",
  "state",
  "addService",
  "rule",
  "selected",
  "onSelectedChange"
);

export type PlasmicMainPageQuestion__OverridesType = {
  root?: Flex__<"div">;
  button?: Flex__<typeof Button>;
  button2?: Flex__<typeof Button>;
  select?: Flex__<typeof Select>;
  centers?: Flex__<typeof ApiRequest>;
  errorpage?: Flex__<typeof Errorpage>;
  emptyPage?: Flex__<typeof EmptyPage>;
  questionItem2?: Flex__<typeof QuestionItem2>;
  snackbar3?: Flex__<typeof Snackbar>;
  button11?: Flex__<typeof Button>;
  button12?: Flex__<typeof Button>;
  modal?: Flex__<typeof AntdModal>;
  questionItemModal?: Flex__<typeof QuestionItemModal>;
};

export interface DefaultMainPageQuestionProps {
  openEdit?: (event: any) => void;
  categpty?: any;
  onCategptyChange?: (val: string) => void;
  onRowClicked?: (rowKey: string, row: any, event: any) => void;
  centerDelete?: () => void;
  onCenterChange?: (val: string) => void;
  restart?: string;
  onRestartChange?: (val: string) => void;
  list?: boolean;
  onListChange2?: (val: string) => void;
  state?: string;
  addService?: (event: any) => void;
  rule?: string;
  selected?: any;
  onSelectedChange?: (val: string) => void;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMainPageQuestion__RenderFunc(props: {
  variants: PlasmicMainPageQuestion__VariantsArgs;
  args: PlasmicMainPageQuestion__ArgsType;
  overrides: PlasmicMainPageQuestion__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "select.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "select.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => "item2"
      },
      {
        path: "button.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "centers.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "centers.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "centers.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "categpty",
        type: "writable",
        variableType: "array",

        valueProp: "categpty",
        onChangeProp: "onCategptyChange"
      },
      {
        path: "center",
        type: "readonly",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ({}),

        onChangeProp: "onCenterChange"
      },
      {
        path: "restart",
        type: "writable",
        variableType: "text",

        valueProp: "restart",
        onChangeProp: "onRestartChange"
      },
      {
        path: "loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => true
      },
      {
        path: "list",
        type: "writable",
        variableType: "boolean",

        valueProp: "list",
        onChangeProp: "onListChange2"
      },
      {
        path: "button2.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "selected",
        type: "writable",
        variableType: "object",

        valueProp: "selected",
        onChangeProp: "onSelectedChange"
      },
      {
        path: "snackbar3.opendialog",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "snackbar3.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ({})
      },
      {
        path: "snackbar3.index",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => []
      },
      {
        path: "button11.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "button12.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "modal.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );

  const $globalActions = useGlobalActions?.();

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_qARqpE4p5tZmJuNxFbTaPz",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
      style={(() => {
        try {
          return { height: "100dvh" };
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return undefined;
          }
          throw e;
        }
      })()}
    >
      <div className={classNames("all", sty.freeBox__ni4EC)}>
        <div className={classNames("all", "__wab_text", sty.text__dok88)}>
          {"\u0633\u0648\u0627\u0644\u0627\u062a \u0641\u0631\u0645"}
        </div>
        <div className={classNames("all", sty.freeBox__ee5Z3)}>
          <Button
            data-plasmic-name={"button"}
            data-plasmic-override={overrides.button}
            className={classNames("__wab_instance", sty.button)}
            color={"success"}
            end={
              <Icon56Icon
                className={classNames("all", sty.svg__uTuCl)}
                role={"img"}
              />
            }
            iconEnd={true}
            label={
              <div className={classNames("all", "__wab_text", sty.text__lYhhT)}>
                {"\u0633\u0648\u0627\u0644 \u062c\u062f\u06cc\u062f"}
              </div>
            }
            loading={generateStateValueProp($state, ["button", "loading"])}
            onClick={async event => {
              const $steps = {};

              $steps["updateModalOpen"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["modal", "open"]
                      },
                      operation: 4
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      const oldValue = $stateGet(objRoot, variablePath);
                      $stateSet(objRoot, variablePath, !oldValue);
                      return !oldValue;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateModalOpen"] != null &&
                typeof $steps["updateModalOpen"] === "object" &&
                typeof $steps["updateModalOpen"].then === "function"
              ) {
                $steps["updateModalOpen"] = await $steps["updateModalOpen"];
              }
            }}
            onLoadingChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["button", "loading"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
          />

          {(() => {
            try {
              return $props.rule == "super_admin";
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <Button
              data-plasmic-name={"button2"}
              data-plasmic-override={overrides.button2}
              className={classNames("__wab_instance", sty.button2)}
              color={"warning"}
              end={
                <Icon56Icon
                  className={classNames("all", sty.svg___6Kr5P)}
                  role={"img"}
                />
              }
              iconEnd={true}
              label={
                <div
                  className={classNames("all", "__wab_text", sty.text__rO46J)}
                >
                  {"\u062e\u062f\u0645\u062a \u062c\u062f\u06cc\u062f"}
                </div>
              }
              loading={generateStateValueProp($state, ["button2", "loading"])}
              onClick={args.addService}
              onLoadingChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, ["button2", "loading"]).apply(
                  null,
                  eventArgs
                );

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            />
          ) : null}
          <div className={classNames("all", sty.freeBox__bcUQy)}>
            <Select
              data-plasmic-name={"select"}
              data-plasmic-override={overrides.select}
              className={classNames("__wab_instance", sty.select)}
              isOpen={generateStateValueProp($state, ["select", "isOpen"])}
              onChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, ["select", "value"]).apply(
                  null,
                  eventArgs
                );

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              onOpenChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, ["select", "isOpen"]).apply(
                  null,
                  eventArgs
                );

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              showLabel={false}
              type={"soft"}
              value={generateStateValueProp($state, ["select", "value"])}
            />
          </div>
        </div>
      </div>
      <div className={classNames("all", sty.freeBox__yHsJ)}>
        <div className={classNames("all", sty.freeBox___6G6W6, "center")}>
          <ApiRequest
            data-plasmic-name={"centers"}
            data-plasmic-override={overrides.centers}
            className={classNames("__wab_instance", sty.centers)}
            errorDisplay={
              <Errorpage
                data-plasmic-name={"errorpage"}
                data-plasmic-override={overrides.errorpage}
                className={classNames("__wab_instance", sty.errorpage)}
              />
            }
            loadingDisplay={
              <div className={classNames("all", sty.freeBox___5FmLk)}>
                <Icon115Icon
                  className={classNames("all", sty.svg__bau3O)}
                  role={"img"}
                />
              </div>
            }
            method={"GET"}
            onError={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["centers", "error"]).apply(
                null,
                eventArgs
              );
            }}
            onLoading={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["centers", "loading"]).apply(
                null,
                eventArgs
              );
            }}
            onSuccess={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["centers", "data"]).apply(
                null,
                eventArgs
              );

              (async data => {
                const $steps = {};

                $steps["updateCenter"] = $state.centers?.data?.success
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["center"]
                        },
                        operation: 0,
                        value: $state.centers?.data?.result
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateCenter"] != null &&
                  typeof $steps["updateCenter"] === "object" &&
                  typeof $steps["updateCenter"].then === "function"
                ) {
                  $steps["updateCenter"] = await $steps["updateCenter"];
                }

                $steps["runCode"] = $state.centers?.data?.success
                  ? (() => {
                      const actionArgs = {
                        customFunction: async () => {
                          return ($state.loading = false);
                        }
                      };
                      return (({ customFunction }) => {
                        return customFunction();
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["runCode"] != null &&
                  typeof $steps["runCode"] === "object" &&
                  typeof $steps["runCode"].then === "function"
                ) {
                  $steps["runCode"] = await $steps["runCode"];
                }

                $steps["updateSelected"] = $state.centers?.data?.success
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["selected"]
                        },
                        operation: 0,
                        value: $state.centers?.data?.result[0]
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateSelected"] != null &&
                  typeof $steps["updateSelected"] === "object" &&
                  typeof $steps["updateSelected"].then === "function"
                ) {
                  $steps["updateSelected"] = await $steps["updateSelected"];
                }
              }).apply(null, eventArgs);
            }}
            params={(() => {
              try {
                return { r: $state.restart };
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
            shouldFetch={(() => {
              try {
                return $state.list;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })()}
            url={"/panel/question"}
          >
            {(() => {
              try {
                return (
                  !!$state.center?.[0] &&
                  Object.keys($state.center[0]).length == 0
                );
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <EmptyPage
                data-plasmic-name={"emptyPage"}
                data-plasmic-override={overrides.emptyPage}
                className={classNames("__wab_instance", sty.emptyPage)}
              />
            ) : null}
            {(() => {
              try {
                return (
                  !!$state.center?.[0] &&
                  Object.keys($state.center[0]).length != 0
                );
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div className={classNames("all", sty.freeBox__xCsMy)}>
                {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                  (() => {
                    try {
                      return $state.center;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return [];
                      }
                      throw e;
                    }
                  })()
                ).map((__plasmic_item_0, __plasmic_idx_0) => {
                  const currentItem = __plasmic_item_0;
                  const currentIndex = __plasmic_idx_0;
                  return (
                    <QuestionItem2
                      data-plasmic-name={"questionItem2"}
                      data-plasmic-override={overrides.questionItem2}
                      className={classNames(
                        "__wab_instance",
                        sty.questionItem2
                      )}
                      currentIndex={currentIndex}
                      currentItem={currentItem}
                      key={currentIndex}
                      onDelet={async event => {
                        const $steps = {};

                        $steps["runCode"] = true
                          ? (() => {
                              const actionArgs = {
                                customFunction: async () => {
                                  return (() => {
                                    $state.snackbar3.data = currentItem;
                                    return ($state.snackbar3.opendialog = true);
                                  })();
                                }
                              };
                              return (({ customFunction }) => {
                                return customFunction();
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["runCode"] != null &&
                          typeof $steps["runCode"] === "object" &&
                          typeof $steps["runCode"].then === "function"
                        ) {
                          $steps["runCode"] = await $steps["runCode"];
                        }
                      }}
                    />
                  );
                })}
              </div>
            ) : null}
          </ApiRequest>
          <div className={classNames("all", sty.freeBox__es8C, ``)}>
            <div className={classNames("all", sty.freeBox__vm64M, ``)}>
              {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                (() => {
                  try {
                    return [2, 3, 4, 5, 6, 7];
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return [];
                    }
                    throw e;
                  }
                })()
              ).map((__plasmic_item_0, __plasmic_idx_0) => {
                const currentItem = __plasmic_item_0;
                const currentIndex = __plasmic_idx_0;
                return (
                  <div
                    cla={"cell"}
                    className={classNames("all", sty.freeBox___2NWn)}
                    key={currentIndex}
                  >
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__jtd3H
                      )}
                    >
                      {"Enter some text"}
                    </div>
                  </div>
                );
              })}
            </div>
            <div className={classNames("all", sty.freeBox__g5Sod)}>
              <div className={classNames("all", sty.freeBox___9Sb0C, ``)}>
                {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                  (() => {
                    try {
                      return [2, 3, 4, 5, 6, 7];
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return [];
                      }
                      throw e;
                    }
                  })()
                ).map((__plasmic_item_0, __plasmic_idx_0) => {
                  const currentItem = __plasmic_item_0;
                  const currentIndex = __plasmic_idx_0;
                  return (
                    <div
                      cla={"cell"}
                      className={classNames("all", sty.freeBox__jlS0H)}
                      key={currentIndex}
                    >
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__ialzs
                        )}
                      >
                        {"Enter some text"}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
      <Snackbar
        data-plasmic-name={"snackbar3"}
        data-plasmic-override={overrides.snackbar3}
        className={classNames("__wab_instance", sty.snackbar3)}
        data={generateStateValueProp($state, ["snackbar3", "data"])}
        index={generateStateValueProp($state, ["snackbar3", "index"])}
        onDataChange={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["snackbar3", "data"]).apply(
            null,
            eventArgs
          );

          if (
            eventArgs.length > 1 &&
            eventArgs[1] &&
            eventArgs[1]._plasmic_state_init_
          ) {
            return;
          }
        }}
        onIndexChange={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["snackbar3", "index"]).apply(
            null,
            eventArgs
          );

          if (
            eventArgs.length > 1 &&
            eventArgs[1] &&
            eventArgs[1]._plasmic_state_init_
          ) {
            return;
          }
        }}
        onOpendialogChange={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["snackbar3", "opendialog"]).apply(
            null,
            eventArgs
          );

          if (
            eventArgs.length > 1 &&
            eventArgs[1] &&
            eventArgs[1]._plasmic_state_init_
          ) {
            return;
          }
        }}
        opendialog={generateStateValueProp($state, ["snackbar3", "opendialog"])}
        slot={"\u062d\u0630\u0641 \u0633\u0648\u0627\u0644"}
        slot2={
          <div className={classNames("all", "__wab_text", sty.text__bPqOb)}>
            <React.Fragment>
              {(() => {
                try {
                  return `آیا از حذف  سوال (${$state.snackbar3.data.question_text}) مطمعن هستید؟`;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "\u0622\u06cc\u0627 \u0627\u0632 \u062d\u0630\u0641  \u0633\u0648\u0627\u0644 ";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
        }
        type={"error"}
      >
        <div className={classNames("all", sty.freeBox___85TM)}>
          <Button
            data-plasmic-name={"button11"}
            data-plasmic-override={overrides.button11}
            className={classNames("__wab_instance", sty.button11)}
            color={"errorDestructive"}
            label={
              <div className={classNames("all", "__wab_text", sty.text__gfaO)}>
                {"\u062d\u0630\u0641"}
              </div>
            }
            loading={generateStateValueProp($state, ["button11", "loading"])}
            onClick={async event => {
              const $steps = {};

              $steps["runCode"] = true
                ? (() => {
                    const actionArgs = {
                      customFunction: async () => {
                        return ($state.button11.loading = true);
                      }
                    };
                    return (({ customFunction }) => {
                      return customFunction();
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runCode"] != null &&
                typeof $steps["runCode"] === "object" &&
                typeof $steps["runCode"].then === "function"
              ) {
                $steps["runCode"] = await $steps["runCode"];
              }

              $steps["invokeGlobalAction"] = true
                ? (() => {
                    const actionArgs = {
                      args: [
                        "POST",
                        "/panel/question/delete",
                        undefined,
                        { id: $state.snackbar3.data.id || null }
                      ]
                    };
                    return $globalActions["Fragment.apiRequest"]?.apply(null, [
                      ...actionArgs.args
                    ]);
                  })()
                : undefined;
              if (
                $steps["invokeGlobalAction"] != null &&
                typeof $steps["invokeGlobalAction"] === "object" &&
                typeof $steps["invokeGlobalAction"].then === "function"
              ) {
                $steps["invokeGlobalAction"] =
                  await $steps["invokeGlobalAction"];
              }

              $steps["invokeGlobalAction2"] = $steps.invokeGlobalAction?.data
                ?.message
                ? (() => {
                    const actionArgs = {
                      args: [
                        $steps.invokeGlobalAction.data.success
                          ? "success"
                          : "error",
                        (() => {
                          try {
                            return $steps.invokeGlobalAction.data.message;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })(),
                        "top-left"
                      ]
                    };
                    return $globalActions["Fragment.showToast"]?.apply(null, [
                      ...actionArgs.args
                    ]);
                  })()
                : undefined;
              if (
                $steps["invokeGlobalAction2"] != null &&
                typeof $steps["invokeGlobalAction2"] === "object" &&
                typeof $steps["invokeGlobalAction2"].then === "function"
              ) {
                $steps["invokeGlobalAction2"] =
                  await $steps["invokeGlobalAction2"];
              }

              $steps["runCode3"] = true
                ? (() => {
                    const actionArgs = {
                      customFunction: async () => {
                        return ($state.restart = Date.now().toString());
                      }
                    };
                    return (({ customFunction }) => {
                      return customFunction();
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runCode3"] != null &&
                typeof $steps["runCode3"] === "object" &&
                typeof $steps["runCode3"].then === "function"
              ) {
                $steps["runCode3"] = await $steps["runCode3"];
              }

              $steps["runCode2"] = true
                ? (() => {
                    const actionArgs = {
                      customFunction: async () => {
                        return ($state.button11.loading = false);
                      }
                    };
                    return (({ customFunction }) => {
                      return customFunction();
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runCode2"] != null &&
                typeof $steps["runCode2"] === "object" &&
                typeof $steps["runCode2"].then === "function"
              ) {
                $steps["runCode2"] = await $steps["runCode2"];
              }
            }}
            onLoadingChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["button11", "loading"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
          />

          <Button
            data-plasmic-name={"button12"}
            data-plasmic-override={overrides.button12}
            className={classNames("__wab_instance", sty.button12)}
            color={"neutral"}
            label={
              <div className={classNames("all", "__wab_text", sty.text__tyq4U)}>
                {"\u0644\u0641\u0648"}
              </div>
            }
            loading={generateStateValueProp($state, ["button12", "loading"])}
            onClick={async event => {
              const $steps = {};

              $steps["runCode"] = true
                ? (() => {
                    const actionArgs = {
                      customFunction: async () => {
                        return ($state.snackbar3.opendialog = false);
                      }
                    };
                    return (({ customFunction }) => {
                      return customFunction();
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runCode"] != null &&
                typeof $steps["runCode"] === "object" &&
                typeof $steps["runCode"].then === "function"
              ) {
                $steps["runCode"] = await $steps["runCode"];
              }
            }}
            onLoadingChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["button12", "loading"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
          />
        </div>
      </Snackbar>
      <AntdModal
        data-plasmic-name={"modal"}
        data-plasmic-override={overrides.modal}
        className={classNames("__wab_instance", sty.modal)}
        defaultStylesClassName={classNames(
          "root_reset_qARqpE4p5tZmJuNxFbTaPz",
          "plasmic_default_styles",
          "plasmic_mixins",
          styleTokensClassNames
        )}
        hideFooter={true}
        modalScopeClassName={sty["modal__modal"]}
        onOpenChange={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["modal", "open"]).apply(
            null,
            eventArgs
          );
        }}
        open={generateStateValueProp($state, ["modal", "open"])}
        title={null}
        trigger={null}
      >
        <div className={classNames("all", sty.freeBox__oO813)}>
          <QuestionItemModal
            data-plasmic-name={"questionItemModal"}
            data-plasmic-override={overrides.questionItemModal}
            add={async () => {
              const $steps = {};

              $steps["runCode"] = true
                ? (() => {
                    const actionArgs = {
                      customFunction: async () => {
                        return (() => {
                          $state.restart += 1;
                          return ($state.modal.open = false);
                        })();
                      }
                    };
                    return (({ customFunction }) => {
                      return customFunction();
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runCode"] != null &&
                typeof $steps["runCode"] === "object" &&
                typeof $steps["runCode"].then === "function"
              ) {
                $steps["runCode"] = await $steps["runCode"];
              }
            }}
            className={classNames("__wab_instance", sty.questionItemModal)}
            onDelet={async event => {
              const $steps = {};

              $steps["updateModalOpen"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["modal", "open"]
                      },
                      operation: 4
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      const oldValue = $stateGet(objRoot, variablePath);
                      $stateSet(objRoot, variablePath, !oldValue);
                      return !oldValue;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateModalOpen"] != null &&
                typeof $steps["updateModalOpen"] === "object" &&
                typeof $steps["updateModalOpen"].then === "function"
              ) {
                $steps["updateModalOpen"] = await $steps["updateModalOpen"];
              }
            }}
          />
        </div>
      </AntdModal>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "button",
    "button2",
    "select",
    "centers",
    "errorpage",
    "emptyPage",
    "questionItem2",
    "snackbar3",
    "button11",
    "button12",
    "modal",
    "questionItemModal"
  ],
  button: ["button"],
  button2: ["button2"],
  select: ["select"],
  centers: ["centers", "errorpage", "emptyPage", "questionItem2"],
  errorpage: ["errorpage"],
  emptyPage: ["emptyPage"],
  questionItem2: ["questionItem2"],
  snackbar3: ["snackbar3", "button11", "button12"],
  button11: ["button11"],
  button12: ["button12"],
  modal: ["modal", "questionItemModal"],
  questionItemModal: ["questionItemModal"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  button: typeof Button;
  button2: typeof Button;
  select: typeof Select;
  centers: typeof ApiRequest;
  errorpage: typeof Errorpage;
  emptyPage: typeof EmptyPage;
  questionItem2: typeof QuestionItem2;
  snackbar3: typeof Snackbar;
  button11: typeof Button;
  button12: typeof Button;
  modal: typeof AntdModal;
  questionItemModal: typeof QuestionItemModal;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMainPageQuestion__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMainPageQuestion__VariantsArgs;
    args?: PlasmicMainPageQuestion__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicMainPageQuestion__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicMainPageQuestion__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMainPageQuestion__ArgProps,
          internalVariantPropNames: PlasmicMainPageQuestion__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMainPageQuestion__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMainPageQuestion";
  } else {
    func.displayName = `PlasmicMainPageQuestion.${nodeName}`;
  }
  return func;
}

export const PlasmicMainPageQuestion = Object.assign(
  // Top-level PlasmicMainPageQuestion renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    button: makeNodeComponent("button"),
    button2: makeNodeComponent("button2"),
    select: makeNodeComponent("select"),
    centers: makeNodeComponent("centers"),
    errorpage: makeNodeComponent("errorpage"),
    emptyPage: makeNodeComponent("emptyPage"),
    questionItem2: makeNodeComponent("questionItem2"),
    snackbar3: makeNodeComponent("snackbar3"),
    button11: makeNodeComponent("button11"),
    button12: makeNodeComponent("button12"),
    modal: makeNodeComponent("modal"),
    questionItemModal: makeNodeComponent("questionItemModal"),

    // Metadata about props expected for PlasmicMainPageQuestion
    internalVariantProps: PlasmicMainPageQuestion__VariantProps,
    internalArgProps: PlasmicMainPageQuestion__ArgProps
  }
);

export default PlasmicMainPageQuestion;
/* prettier-ignore-end */
