/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qARqpE4p5tZmJuNxFbTaPz
// Component: zJ2RueI-cLbg

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicStatusIcon.module.css"; // plasmic-import: zJ2RueI-cLbg/css

import ClockIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__Clock"; // plasmic-import: sBP7srrq0jxO/icon
import CircleCheckIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__CircleCheck"; // plasmic-import: KkttdV01iFXR/icon
import WashDrycleanOffIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__WashDrycleanOff"; // plasmic-import: QFNdjGQULUYm/icon
import TimeDurationOffIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__TimeDurationOff"; // plasmic-import: SHVGkAq8tSC4/icon
import CircleDashedCheckIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__CircleDashedCheck"; // plasmic-import: Zi9Pm0Fuq1Kb/icon

createPlasmicElementProxy;

export type PlasmicStatusIcon__VariantMembers = {
  status: "pending" | "confirmed" | "canceled" | "rejected" | "completed";
  textcolor: "textcolor";
};
export type PlasmicStatusIcon__VariantsArgs = {
  status?: SingleChoiceArg<
    "pending" | "confirmed" | "canceled" | "rejected" | "completed"
  >;
  textcolor?: SingleBooleanChoiceArg<"textcolor">;
};
type VariantPropType = keyof PlasmicStatusIcon__VariantsArgs;
export const PlasmicStatusIcon__VariantProps = new Array<VariantPropType>(
  "status",
  "textcolor"
);

export type PlasmicStatusIcon__ArgsType = {};
type ArgPropType = keyof PlasmicStatusIcon__ArgsType;
export const PlasmicStatusIcon__ArgProps = new Array<ArgPropType>();

export type PlasmicStatusIcon__OverridesType = {
  root?: Flex__<"div">;
  svg?: Flex__<"svg">;
};

export interface DefaultStatusIconProps {
  status?: SingleChoiceArg<
    "pending" | "confirmed" | "canceled" | "rejected" | "completed"
  >;
  textcolor?: SingleBooleanChoiceArg<"textcolor">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicStatusIcon__RenderFunc(props: {
  variants: PlasmicStatusIcon__VariantsArgs;
  args: PlasmicStatusIcon__ArgsType;
  overrides: PlasmicStatusIcon__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "status",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.status
      },
      {
        path: "textcolor",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.textcolor
      },
      {
        path: "unnamedGroupOfVariants",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props.unnamedGroupOfVariants
      },
      {
        path: "unnamedGroupOfVariants2",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props.unnamedGroupOfVariants2
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_qARqpE4p5tZmJuNxFbTaPz",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootstatus_canceled]: hasVariant($state, "status", "canceled"),
          [sty.rootstatus_completed]: hasVariant($state, "status", "completed"),
          [sty.rootstatus_confirmed]: hasVariant($state, "status", "confirmed"),
          [sty.rootstatus_pending]: hasVariant($state, "status", "pending"),
          [sty.rootstatus_rejected]: hasVariant($state, "status", "rejected"),
          [sty.rootstatus_rejected_textcolor]:
            hasVariant($state, "textcolor", "textcolor") &&
            hasVariant($state, "status", "rejected"),
          [sty.roottextcolor_status_canceled]:
            hasVariant($state, "textcolor", "textcolor") &&
            hasVariant($state, "status", "canceled"),
          [sty.roottextcolor_status_confirmed]:
            hasVariant($state, "textcolor", "textcolor") &&
            hasVariant($state, "status", "confirmed"),
          [sty.roottextcolor_status_pending]:
            hasVariant($state, "textcolor", "textcolor") &&
            hasVariant($state, "status", "pending")
        }
      )}
    >
      <PlasmicIcon__
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        PlasmicIconType={
          hasVariant($state, "status", "completed")
            ? CircleDashedCheckIcon
            : hasVariant($state, "status", "rejected")
              ? TimeDurationOffIcon
              : hasVariant($state, "status", "canceled")
                ? WashDrycleanOffIcon
                : hasVariant($state, "status", "confirmed")
                  ? CircleCheckIcon
                  : ClockIcon
        }
        className={classNames("all", sty.svg, {
          [sty.svgstatus_canceled]: hasVariant($state, "status", "canceled"),
          [sty.svgstatus_completed]: hasVariant($state, "status", "completed"),
          [sty.svgstatus_confirmed]: hasVariant($state, "status", "confirmed"),
          [sty.svgstatus_pending]: hasVariant($state, "status", "pending"),
          [sty.svgstatus_rejected]: hasVariant($state, "status", "rejected")
        })}
        role={"img"}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStatusIcon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStatusIcon__VariantsArgs;
    args?: PlasmicStatusIcon__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicStatusIcon__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicStatusIcon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStatusIcon__ArgProps,
          internalVariantPropNames: PlasmicStatusIcon__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStatusIcon__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStatusIcon";
  } else {
    func.displayName = `PlasmicStatusIcon.${nodeName}`;
  }
  return func;
}

export const PlasmicStatusIcon = Object.assign(
  // Top-level PlasmicStatusIcon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicStatusIcon
    internalVariantProps: PlasmicStatusIcon__VariantProps,
    internalArgProps: PlasmicStatusIcon__ArgProps
  }
);

export default PlasmicStatusIcon;
/* prettier-ignore-end */
