// This is a skeleton starter React page generated by Plasmic.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../../../components/plasmic/sayban/PlasmicGlobalContextsProvider";
import { StyleTokensProvider } from "../../../components/plasmic/sayban/PlasmicStyleTokensProvider";
import { PlasmicLogin } from "../../../components/plasmic/sayban/PlasmicLogin";
import { useRouter } from "next/router";
import { PlasmicQueryDataProvider } from "@plasmicapp/react-web/lib/query";

function Login() {
  const router = useRouter();

  return (
    <GlobalContextsProvider>
      <PlasmicQueryDataProvider>
        <PageParamsProvider__
          route={router?.pathname}
          params={router?.query}
          query={router?.query}
        >
          <StyleTokensProvider>
            <PlasmicLogin />
          </StyleTokensProvider>
        </PageParamsProvider__>
      </PlasmicQueryDataProvider>
    </GlobalContextsProvider>
  );
}

export default Login;
