<<<<<<< HEAD
"use client";

import { usePathname } from "next/navigation";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../../../components/plasmic/website_starter/PlasmicGlobalContextsProvider";
import { PlasmicHomepage } from "../../../components/plasmic/website_starter/PlasmicHomepage";

export default function Homepage() {
  const pathname = usePathname() || "/";

  // "/centers/sport/football" → ["centers","sport","football"]
  const parts = pathname.split("/").filter(Boolean);

  const page = parts[0] || undefined; // ← تغییر از null به undefined
  const slug = parts.slice(1);

  const params = { page, slug };

  return (
    <GlobalContextsProvider>
      <PageParamsProvider__
        route={pathname}
        params={params}
        query={params}
      >
        <PlasmicHomepage />
      </PageParamsProvider__>
    </GlobalContextsProvider>
  );
}
=======
// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../../../components/plasmic/sayban/PlasmicGlobalContextsProvider";
import { StyleTokensProvider } from "../../../components/plasmic/sayban/PlasmicStyleTokensProvider";

import { PlasmicHomepage } from "../../../components/plasmic/sayban/PlasmicHomepage";
import { useRouter } from "next/router";
import { PlasmicQueryDataProvider } from "@plasmicapp/react-web/lib/query";

function Homepage() {
  // Use PlasmicHomepage to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicHomepage are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicHomepage is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).

  return (
    <GlobalContextsProvider>
      <PlasmicQueryDataProvider>
        <PageParamsProvider__
          route={useRouter()?.pathname}
          params={useRouter()?.query}
          query={useRouter()?.query}
        >
          <StyleTokensProvider>
            <PlasmicHomepage />
          </StyleTokensProvider>
        </PageParamsProvider__>
      </PlasmicQueryDataProvider>
    </GlobalContextsProvider>
  );
}

export default Homepage;
>>>>>>> plasmicops/rQ6tUgoS/newMain
