/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sqPBLwEBBKHA2WDuGb17eV

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: sqPBLwEBBKHA2WDuGb17eV/projectModule

<<<<<<< HEAD
import projectcss from "./plasmic.css"; // plasmic-import: sqPBLwEBBKHA2WDuGb17eV/projectcss

const data = {
  base: `${projectcss.plasmic_tokens}`,
=======
const data = {
  base: `${"plasmic_tokens_sqPBLwEBBKHA2WDuGb17eV"}`,
>>>>>>> plasmicops/rQ6tUgoS/newMain
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
