/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qARqpE4p5tZmJuNxFbTaPz
// Component: m-UDUThzN-63

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { SwiperSlider } from "@/components/SwiperSlider"; // plasmic-import: byElilYJKEPk/codeComponent
import ToolsItem from "../../ToolsItem"; // plasmic-import: M_mJLv9BDPmq/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import Item from "../../Item"; // plasmic-import: lqR7VxT6h9YH/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: qARqpE4p5tZmJuNxFbTaPz/projectcss
import sty from "./PlasmicHome.module.css"; // plasmic-import: m-UDUThzN-63/css

createPlasmicElementProxy;

export type PlasmicHome__VariantMembers = {
  search: "search";
};
export type PlasmicHome__VariantsArgs = {
  search?: SingleBooleanChoiceArg<"search">;
};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>("search");

export type PlasmicHome__ArgsType = {
  onSearchChange?: (val: any) => void;
  categories?: any;
  categori?: any;
  onCategoriChange?: (val: string) => void;
  onCategori?: () => void;
};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>(
  "onSearchChange",
  "categories",
  "categori",
  "onCategoriChange",
  "onCategori"
);

export type PlasmicHome__OverridesType = {
  root?: Flex__<"div">;
  swiperSlider2?: Flex__<typeof SwiperSlider>;
  toolsItem?: Flex__<typeof ToolsItem>;
  reveal?: Flex__<typeof Reveal>;
  item?: Flex__<typeof Item>;
};

export interface DefaultHomeProps {
  onSearchChange?: (val: any) => void;
  categories?: any;
  categori?: any;
  onCategoriChange?: (val: string) => void;
  onCategori?: () => void;
  search?: SingleBooleanChoiceArg<"search">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "search",
        type: "writable",
        variableType: "variant",

        valueProp: "search",
        onChangeProp: "onSearchChange"
      },
      {
        path: "swiperSlider2.activeSlideIndex",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0
      },
      {
        path: "swiperSlider2.lockSlides",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "categori",
        type: "writable",
        variableType: "object",

        valueProp: "categori",
        onChangeProp: "onCategoriChange"
      },
      {
        path: "item[].center",
        type: "private",
        variableType: "object"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        { [sty.rootsearch]: hasVariant($state, "search", "search") }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__dzcLe, {
          [sty.freeBoxsearch__dzcLeMh4IK]: hasVariant(
            $state,
            "search",
            "search"
          )
        })}
      >
        <SwiperSlider
          data-plasmic-name={"swiperSlider2"}
          data-plasmic-override={overrides.swiperSlider2}
          activeBulletColor={"#ffffff"}
          activeSlideIndex={generateStateValueProp($state, [
            "swiperSlider2",
            "activeSlideIndex"
          ])}
          autoplay={true}
          autoplayDelay={5000}
          bulletColor={"#888888"}
          className={classNames("__wab_instance", sty.swiperSlider2)}
          disablePaginationClick={false}
          lockSlides={generateStateValueProp($state, [
            "swiperSlider2",
            "lockSlides"
          ])}
          loop={true}
          onActiveSlideIndexChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "swiperSlider2",
              "activeSlideIndex"
            ]).apply(null, eventArgs);
          }}
          onLockSlidesChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "swiperSlider2",
              "lockSlides"
            ]).apply(null, eventArgs);
          }}
          showNavigationButtons={false}
          showPagination={true}
        >
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__redDh)}
            displayHeight={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "120px"
                : "200px"
            }
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/website_starter/images/image7.png",
              fullWidth: 800,
              fullHeight: 297,
              aspectRatio: undefined
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img___58Ai3)}
            displayHeight={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "120px"
                : "200px"
            }
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/website_starter/images/image8.png",
              fullWidth: 409,
              fullHeight: 123,
              aspectRatio: undefined
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__yq35R)}
            displayHeight={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "120px"
                : "200px"
            }
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/website_starter/images/image9.png",
              fullWidth: 413,
              fullHeight: 122,
              aspectRatio: undefined
            }}
          />
        </SwiperSlider>
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__muDck, {
          [sty.freeBoxsearch__muDckMh4IK]: hasVariant(
            $state,
            "search",
            "search"
          )
        })}
      >
        <div
          className={classNames(projectcss.all, sty.freeBox___0GJcQ, {
            [sty.freeBoxsearch___0GJcQMh4IK]: hasVariant(
              $state,
              "search",
              "search"
            )
          })}
        >
          {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
            (() => {
              try {
                return $props.categories;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return [];
                }
                throw e;
              }
            })()
          ).map((__plasmic_item_0, __plasmic_idx_0) => {
            const currentItem = __plasmic_item_0;
            const currentIndex = __plasmic_idx_0;
            return (
              <ToolsItem
                data-plasmic-name={"toolsItem"}
                data-plasmic-override={overrides.toolsItem}
                back={true}
                className={classNames("__wab_instance", sty.toolsItem, {
                  [sty.toolsItemsearch]: hasVariant($state, "search", "search")
                })}
                data={(() => {
                  try {
                    return currentItem;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
                key={currentIndex}
                onClick={async event => {
                  const $steps = {};

                  $steps["updateCategori"] = true
                    ? (() => {
                        const actionArgs = {
                          variable: {
                            objRoot: $state,
                            variablePath: ["categori"]
                          },
                          operation: 0,
                          value: currentItem
                        };
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;

                          $stateSet(objRoot, variablePath, value);
                          return value;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateCategori"] != null &&
                    typeof $steps["updateCategori"] === "object" &&
                    typeof $steps["updateCategori"].then === "function"
                  ) {
                    $steps["updateCategori"] = await $steps["updateCategori"];
                  }

                  $steps["runOnCategori"] = true
                    ? (() => {
                        const actionArgs = { eventRef: $props["onCategori"] };
                        return (({ eventRef, args }) => {
                          return eventRef?.(...(args ?? []));
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["runOnCategori"] != null &&
                    typeof $steps["runOnCategori"] === "object" &&
                    typeof $steps["runOnCategori"].then === "function"
                  ) {
                    $steps["runOnCategori"] = await $steps["runOnCategori"];
                  }
                }}
              />
            );
          })}
        </div>
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox___8ZSjn, {
          [sty.freeBoxsearch___8ZSjnMh4IK]: hasVariant(
            $state,
            "search",
            "search"
          )
        })}
      >
        <Reveal
          data-plasmic-name={"reveal"}
          data-plasmic-override={overrides.reveal}
          cascade={true}
          className={classNames("__wab_instance", sty.reveal)}
          damping={0.2}
          effect={"fade"}
          triggerOnce={true}
        >
          {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))([
            2, 3, 4
          ]).map((__plasmic_item_0, __plasmic_idx_0) => {
            const currentItem = __plasmic_item_0;
            const currentIndex = __plasmic_idx_0;
            return (
              <Item
                data-plasmic-name={"item"}
                data-plasmic-override={overrides.item}
                className={classNames("__wab_instance", sty.item, {
                  [sty.itemsearch]: hasVariant($state, "search", "search")
                })}
                key={currentIndex}
                onCenterChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "item",
                    __plasmic_idx_0,
                    "center"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
              />
            );
          })}
        </Reveal>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "swiperSlider2", "toolsItem", "reveal", "item"],
  swiperSlider2: ["swiperSlider2"],
  toolsItem: ["toolsItem"],
  reveal: ["reveal", "item"],
  item: ["item"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  swiperSlider2: typeof SwiperSlider;
  toolsItem: typeof ToolsItem;
  reveal: typeof Reveal;
  item: typeof Item;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHome__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHome__ArgProps,
          internalVariantPropNames: PlasmicHome__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    swiperSlider2: makeNodeComponent("swiperSlider2"),
    toolsItem: makeNodeComponent("toolsItem"),
    reveal: makeNodeComponent("reveal"),
    item: makeNodeComponent("item"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
