// Center.tsx
// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.

import * as React from "react";
import {
  PlasmicCenter,
  DefaultCenterProps
} from "./plasmic/sayban/PlasmicCenter";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// اضافه کنیم
import moment from "jalali-moment";

export interface CenterProps extends DefaultCenterProps {}

function Center_(props: CenterProps, ref: HTMLElementRefOf<"div">) {
  return (
    <PlasmicCenter
      root={{ ref }}
      {...props}
      
      // 🔥 مهم‌ترین خط
      // ارسال خود moment به عنوان یک Object برای استفاده در Plasmic
      jalali={moment}
    />
  );
}

const Center = React.forwardRef(Center_);
export default Center;
