// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicSubcategories,
  DefaultSubcategoriesProps
} from "./plasmic/sayban/PlasmicSubcategories";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface SubcategoriesProps extends Omit<DefaultSubcategoriesProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultSubcategoriesProps altogether and have
// total control over the props for your component.
export interface SubcategoriesProps extends DefaultSubcategoriesProps {}

function Subcategories_(
  props: SubcategoriesProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicSubcategories to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicSubcategories are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all SubcategoriesProps here, but feel free
  // to do whatever works for you.

  return <PlasmicSubcategories root={{ ref }} {...props} />;
}

const Subcategories = React.forwardRef(Subcategories_);
export default Subcategories;
