/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jkU633o1Cz7HrJdwdxhVHk

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectModule

<<<<<<< HEAD
import projectcss from "./plasmic.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss

const data = {
  base: `${projectcss.plasmic_tokens}`,
=======
const data = {
  base: `${"plasmic_tokens_jkU633o1Cz7HrJdwdxhVHk"}`,
>>>>>>> plasmicops/rQ6tUgoS/newMain
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
