/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5dGW8Awro3qq8Hh5MveXLP

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 5dGW8Awro3qq8Hh5MveXLP/projectModule

<<<<<<< HEAD
import projectcss from "./plasmic.css"; // plasmic-import: 5dGW8Awro3qq8Hh5MveXLP/projectcss

const data = {
  base: `${projectcss.plasmic_tokens}`,
=======
const data = {
  base: `${"plasmic_tokens_5dGW8Awro3qq8Hh5MveXLP"}`,
>>>>>>> plasmicops/rQ6tUgoS/newMain
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
